#pragma once

// GENERATED by tools/metal-gen/generate.purr from the metal-cpp headers — DO NOT EDIT.
// Regenerated at release time (tools/metal-gen/regenerate.sh).

/**
 * @file types.hpp
 * @brief gpu.metal — the `mtl.<Name>` cheatah interface to Apple's Metal API (via metal-cpp).
 *
 * `using` aliases for every Metal/Foundation class, enum and constant in `cheatah::gpu::metal`,
 * so `import gpu.metal as mtl` lets a cheatah program call Metal the SAME way it calls Vulkan:
 * `mtl.CreateSystemDefaultDevice()`, `mtl.Device`, `mtl.Buffer`, `mtl.ResourceStorageModeShared`.
 * The raw `MTL::` / `NS::` names remain usable in cpp{} escape hatches.
 */

#include "metal.hpp"

namespace cheatah::gpu::metal {

// --- entry points (free functions, called like vk.CreateInstance) ---
inline ::MTL::Device* CreateSystemDefaultDevice() { return ::MTL::CreateSystemDefaultDevice(); }

// --- object types: mtl.Device, mtl.Buffer, … (aliases of every Metal class) ---
using AccelerationStructureCommandEncoder = ::MTL::AccelerationStructureCommandEncoder;
using AccelerationStructurePassSampleBufferAttachmentDescriptor =
    ::MTL::AccelerationStructurePassSampleBufferAttachmentDescriptor;
using AccelerationStructurePassSampleBufferAttachmentDescriptorArray =
    ::MTL::AccelerationStructurePassSampleBufferAttachmentDescriptorArray;
using AccelerationStructurePassDescriptor = ::MTL::AccelerationStructurePassDescriptor;
using AccelerationStructureDescriptor = ::MTL::AccelerationStructureDescriptor;
using AccelerationStructureGeometryDescriptor = ::MTL::AccelerationStructureGeometryDescriptor;
using PrimitiveAccelerationStructureDescriptor = ::MTL::PrimitiveAccelerationStructureDescriptor;
using AccelerationStructureTriangleGeometryDescriptor =
    ::MTL::AccelerationStructureTriangleGeometryDescriptor;
using AccelerationStructureBoundingBoxGeometryDescriptor =
    ::MTL::AccelerationStructureBoundingBoxGeometryDescriptor;
using MotionKeyframeData = ::MTL::MotionKeyframeData;
using AccelerationStructureMotionTriangleGeometryDescriptor =
    ::MTL::AccelerationStructureMotionTriangleGeometryDescriptor;
using AccelerationStructureMotionBoundingBoxGeometryDescriptor =
    ::MTL::AccelerationStructureMotionBoundingBoxGeometryDescriptor;
using AccelerationStructureCurveGeometryDescriptor =
    ::MTL::AccelerationStructureCurveGeometryDescriptor;
using AccelerationStructureMotionCurveGeometryDescriptor =
    ::MTL::AccelerationStructureMotionCurveGeometryDescriptor;
using InstanceAccelerationStructureDescriptor = ::MTL::InstanceAccelerationStructureDescriptor;
using IndirectInstanceAccelerationStructureDescriptor =
    ::MTL::IndirectInstanceAccelerationStructureDescriptor;
using AccelerationStructure = ::MTL::AccelerationStructure;
using Allocation = ::MTL::Allocation;
using ArgumentEncoder = ::MTL::ArgumentEncoder;
using Type = ::MTL::Type;
using StructMember = ::MTL::StructMember;
using StructType = ::MTL::StructType;
using ArrayType = ::MTL::ArrayType;
using PointerType = ::MTL::PointerType;
using TextureReferenceType = ::MTL::TextureReferenceType;
using TensorAuxiliaryPlaneType = ::MTL::TensorAuxiliaryPlaneType;
using TensorReferenceType = ::MTL::TensorReferenceType;
using Argument = ::MTL::Argument;
using Binding = ::MTL::Binding;
using BufferBinding = ::MTL::BufferBinding;
using ThreadgroupBinding = ::MTL::ThreadgroupBinding;
using TextureBinding = ::MTL::TextureBinding;
using ObjectPayloadBinding = ::MTL::ObjectPayloadBinding;
using TensorBinding = ::MTL::TensorBinding;
using BinaryArchiveDescriptor = ::MTL::BinaryArchiveDescriptor;
using BinaryArchive = ::MTL::BinaryArchive;
using BlitCommandEncoder = ::MTL::BlitCommandEncoder;
using BlitPassSampleBufferAttachmentDescriptor = ::MTL::BlitPassSampleBufferAttachmentDescriptor;
using BlitPassSampleBufferAttachmentDescriptorArray =
    ::MTL::BlitPassSampleBufferAttachmentDescriptorArray;
using BlitPassDescriptor = ::MTL::BlitPassDescriptor;
using Buffer = ::MTL::Buffer;
using CaptureDescriptor = ::MTL::CaptureDescriptor;
using CaptureManager = ::MTL::CaptureManager;
using CaptureScope = ::MTL::CaptureScope;
using CommandBufferDescriptor = ::MTL::CommandBufferDescriptor;
using CommandBufferEncoderInfo = ::MTL::CommandBufferEncoderInfo;
using CommandBuffer = ::MTL::CommandBuffer;
using CommandEncoder = ::MTL::CommandEncoder;
using CommandQueue = ::MTL::CommandQueue;
using CommandQueueDescriptor = ::MTL::CommandQueueDescriptor;
using ComputeCommandEncoder = ::MTL::ComputeCommandEncoder;
using ComputePassSampleBufferAttachmentDescriptor =
    ::MTL::ComputePassSampleBufferAttachmentDescriptor;
using ComputePassSampleBufferAttachmentDescriptorArray =
    ::MTL::ComputePassSampleBufferAttachmentDescriptorArray;
using ComputePassDescriptor = ::MTL::ComputePassDescriptor;
using ComputePipelineReflection = ::MTL::ComputePipelineReflection;
using ComputePipelineDescriptor = ::MTL::ComputePipelineDescriptor;
using ComputePipelineState = ::MTL::ComputePipelineState;
using Counter = ::MTL::Counter;
using CounterSet = ::MTL::CounterSet;
using CounterSampleBufferDescriptor = ::MTL::CounterSampleBufferDescriptor;
using CounterSampleBuffer = ::MTL::CounterSampleBuffer;
using StencilDescriptor = ::MTL::StencilDescriptor;
using DepthStencilDescriptor = ::MTL::DepthStencilDescriptor;
using DepthStencilState = ::MTL::DepthStencilState;
using ArgumentDescriptor = ::MTL::ArgumentDescriptor;
using Architecture = ::MTL::Architecture;
using Device = ::MTL::Device;
using Drawable = ::MTL::Drawable;
using DynamicLibrary = ::MTL::DynamicLibrary;
using Event = ::MTL::Event;
using SharedEventListener = ::MTL::SharedEventListener;
using SharedEvent = ::MTL::SharedEvent;
using SharedEventHandle = ::MTL::SharedEventHandle;
using Fence = ::MTL::Fence;
using FunctionConstantValues = ::MTL::FunctionConstantValues;
using FunctionDescriptor = ::MTL::FunctionDescriptor;
using IntersectionFunctionDescriptor = ::MTL::IntersectionFunctionDescriptor;
using FunctionHandle = ::MTL::FunctionHandle;
using LogContainer = ::MTL::LogContainer;
using FunctionLogDebugLocation = ::MTL::FunctionLogDebugLocation;
using FunctionLog = ::MTL::FunctionLog;
using FunctionStitchingAttribute = ::MTL::FunctionStitchingAttribute;
using FunctionStitchingAttributeAlwaysInline = ::MTL::FunctionStitchingAttributeAlwaysInline;
using FunctionStitchingNode = ::MTL::FunctionStitchingNode;
using FunctionStitchingInputNode = ::MTL::FunctionStitchingInputNode;
using FunctionStitchingFunctionNode = ::MTL::FunctionStitchingFunctionNode;
using FunctionStitchingGraph = ::MTL::FunctionStitchingGraph;
using StitchedLibraryDescriptor = ::MTL::StitchedLibraryDescriptor;
using HeapDescriptor = ::MTL::HeapDescriptor;
using Heap = ::MTL::Heap;
using IndirectCommandBufferDescriptor = ::MTL::IndirectCommandBufferDescriptor;
using IndirectCommandBuffer = ::MTL::IndirectCommandBuffer;
using IndirectRenderCommand = ::MTL::IndirectRenderCommand;
using IndirectComputeCommand = ::MTL::IndirectComputeCommand;
using IntersectionFunctionTableDescriptor = ::MTL::IntersectionFunctionTableDescriptor;
using IntersectionFunctionTable = ::MTL::IntersectionFunctionTable;
using IOCommandBuffer = ::MTL::IOCommandBuffer;
using IOCommandQueue = ::MTL::IOCommandQueue;
using IOScratchBuffer = ::MTL::IOScratchBuffer;
using IOScratchBufferAllocator = ::MTL::IOScratchBufferAllocator;
using IOCommandQueueDescriptor = ::MTL::IOCommandQueueDescriptor;
using IOFileHandle = ::MTL::IOFileHandle;
using VertexAttribute = ::MTL::VertexAttribute;
using Attribute = ::MTL::Attribute;
using FunctionConstant = ::MTL::FunctionConstant;
using Function = ::MTL::Function;
using CompileOptions = ::MTL::CompileOptions;
using FunctionReflection = ::MTL::FunctionReflection;
using Library = ::MTL::Library;
using LinkedFunctions = ::MTL::LinkedFunctions;
using LogState = ::MTL::LogState;
using LogStateDescriptor = ::MTL::LogStateDescriptor;
using ParallelRenderCommandEncoder = ::MTL::ParallelRenderCommandEncoder;
using PipelineBufferDescriptor = ::MTL::PipelineBufferDescriptor;
using PipelineBufferDescriptorArray = ::MTL::PipelineBufferDescriptorArray;
using RasterizationRateSampleArray = ::MTL::RasterizationRateSampleArray;
using RasterizationRateLayerDescriptor = ::MTL::RasterizationRateLayerDescriptor;
using RasterizationRateLayerArray = ::MTL::RasterizationRateLayerArray;
using RasterizationRateMapDescriptor = ::MTL::RasterizationRateMapDescriptor;
using RasterizationRateMap = ::MTL::RasterizationRateMap;
using RenderCommandEncoder = ::MTL::RenderCommandEncoder;
using RenderPassAttachmentDescriptor = ::MTL::RenderPassAttachmentDescriptor;
using RenderPassColorAttachmentDescriptor = ::MTL::RenderPassColorAttachmentDescriptor;
using RenderPassDepthAttachmentDescriptor = ::MTL::RenderPassDepthAttachmentDescriptor;
using RenderPassStencilAttachmentDescriptor = ::MTL::RenderPassStencilAttachmentDescriptor;
using RenderPassColorAttachmentDescriptorArray = ::MTL::RenderPassColorAttachmentDescriptorArray;
using RenderPassSampleBufferAttachmentDescriptor =
    ::MTL::RenderPassSampleBufferAttachmentDescriptor;
using RenderPassSampleBufferAttachmentDescriptorArray =
    ::MTL::RenderPassSampleBufferAttachmentDescriptorArray;
using RenderPassDescriptor = ::MTL::RenderPassDescriptor;
using RenderPipelineColorAttachmentDescriptor = ::MTL::RenderPipelineColorAttachmentDescriptor;
using LogicalToPhysicalColorAttachmentMap = ::MTL::LogicalToPhysicalColorAttachmentMap;
using RenderPipelineReflection = ::MTL::RenderPipelineReflection;
using RenderPipelineDescriptor = ::MTL::RenderPipelineDescriptor;
using RenderPipelineFunctionsDescriptor = ::MTL::RenderPipelineFunctionsDescriptor;
using RenderPipelineState = ::MTL::RenderPipelineState;
using RenderPipelineColorAttachmentDescriptorArray =
    ::MTL::RenderPipelineColorAttachmentDescriptorArray;
using TileRenderPipelineColorAttachmentDescriptor =
    ::MTL::TileRenderPipelineColorAttachmentDescriptor;
using TileRenderPipelineColorAttachmentDescriptorArray =
    ::MTL::TileRenderPipelineColorAttachmentDescriptorArray;
using TileRenderPipelineDescriptor = ::MTL::TileRenderPipelineDescriptor;
using MeshRenderPipelineDescriptor = ::MTL::MeshRenderPipelineDescriptor;
using ResidencySetDescriptor = ::MTL::ResidencySetDescriptor;
using ResidencySet = ::MTL::ResidencySet;
using Resource = ::MTL::Resource;
using ResourceStateCommandEncoder = ::MTL::ResourceStateCommandEncoder;
using ResourceStatePassSampleBufferAttachmentDescriptor =
    ::MTL::ResourceStatePassSampleBufferAttachmentDescriptor;
using ResourceStatePassSampleBufferAttachmentDescriptorArray =
    ::MTL::ResourceStatePassSampleBufferAttachmentDescriptorArray;
using ResourceStatePassDescriptor = ::MTL::ResourceStatePassDescriptor;
using ResourceViewPoolDescriptor = ::MTL::ResourceViewPoolDescriptor;
using ResourceViewPool = ::MTL::ResourceViewPool;
using SamplerDescriptor = ::MTL::SamplerDescriptor;
using SamplerState = ::MTL::SamplerState;
using BufferLayoutDescriptor = ::MTL::BufferLayoutDescriptor;
using BufferLayoutDescriptorArray = ::MTL::BufferLayoutDescriptorArray;
using AttributeDescriptor = ::MTL::AttributeDescriptor;
using AttributeDescriptorArray = ::MTL::AttributeDescriptorArray;
using StageInputOutputDescriptor = ::MTL::StageInputOutputDescriptor;
using TensorExtents = ::MTL::TensorExtents;
using TensorAuxiliaryPlaneDescriptor = ::MTL::TensorAuxiliaryPlaneDescriptor;
using TensorAuxiliaryPlaneDescriptorMap = ::MTL::TensorAuxiliaryPlaneDescriptorMap;
using TensorDescriptor = ::MTL::TensorDescriptor;
using TensorBufferAttachments = ::MTL::TensorBufferAttachments;
using TensorAuxiliaryPlane = ::MTL::TensorAuxiliaryPlane;
using Tensor = ::MTL::Tensor;
using SharedTextureHandle = ::MTL::SharedTextureHandle;
using TextureDescriptor = ::MTL::TextureDescriptor;
using TextureViewDescriptor = ::MTL::TextureViewDescriptor;
using Texture = ::MTL::Texture;
using TextureViewPool = ::MTL::TextureViewPool;
using VertexBufferLayoutDescriptor = ::MTL::VertexBufferLayoutDescriptor;
using VertexBufferLayoutDescriptorArray = ::MTL::VertexBufferLayoutDescriptorArray;
using VertexAttributeDescriptor = ::MTL::VertexAttributeDescriptor;
using VertexAttributeDescriptorArray = ::MTL::VertexAttributeDescriptorArray;
using VertexDescriptor = ::MTL::VertexDescriptor;
using VisibleFunctionTableDescriptor = ::MTL::VisibleFunctionTableDescriptor;
using VisibleFunctionTable = ::MTL::VisibleFunctionTable;
using Size = ::MTL::Size;
using Origin = ::MTL::Origin;
using Region = ::MTL::Region;
using ScissorRect = ::MTL::ScissorRect;
using Viewport = ::MTL::Viewport;
using ClearColor = ::MTL::ClearColor;
using SamplePosition = ::MTL::SamplePosition;
using Coordinate2D = ::MTL::Coordinate2D;
// --- Foundation glue: mtl.String, mtl.Error, mtl.AutoreleasePool, … ---
using Object = ::NS::Object;
using String = ::NS::String;
using Error = ::NS::Error;
using AutoreleasePool = ::NS::AutoreleasePool;
using Array = ::NS::Array;
using Dictionary = ::NS::Dictionary;
using Number = ::NS::Number;
using Data = ::NS::Data;
using URL = ::NS::URL;
using Bundle = ::NS::Bundle;
inline constexpr auto UTF8StringEncoding = ::NS::UTF8StringEncoding;
inline constexpr auto ASCIIStringEncoding = ::NS::ASCIIStringEncoding;
inline constexpr auto UnicodeStringEncoding = ::NS::UnicodeStringEncoding;

// --- enums + constants: mtl.ResourceOptions, mtl.ResourceStorageModeShared, … ---
using MatrixLayout = ::MTL::MatrixLayout;
inline constexpr auto MatrixLayoutColumnMajor = ::MTL::MatrixLayoutColumnMajor;
inline constexpr auto MatrixLayoutRowMajor = ::MTL::MatrixLayoutRowMajor;
using MotionBorderMode = ::MTL::MotionBorderMode;
inline constexpr auto MotionBorderModeClamp = ::MTL::MotionBorderModeClamp;
inline constexpr auto MotionBorderModeVanish = ::MTL::MotionBorderModeVanish;
using CurveType = ::MTL::CurveType;
inline constexpr auto CurveTypeRound = ::MTL::CurveTypeRound;
inline constexpr auto CurveTypeFlat = ::MTL::CurveTypeFlat;
using CurveBasis = ::MTL::CurveBasis;
inline constexpr auto CurveBasisBSpline = ::MTL::CurveBasisBSpline;
inline constexpr auto CurveBasisCatmullRom = ::MTL::CurveBasisCatmullRom;
inline constexpr auto CurveBasisLinear = ::MTL::CurveBasisLinear;
inline constexpr auto CurveBasisBezier = ::MTL::CurveBasisBezier;
using CurveEndCaps = ::MTL::CurveEndCaps;
inline constexpr auto CurveEndCapsNone = ::MTL::CurveEndCapsNone;
inline constexpr auto CurveEndCapsDisk = ::MTL::CurveEndCapsDisk;
inline constexpr auto CurveEndCapsSphere = ::MTL::CurveEndCapsSphere;
using AccelerationStructureInstanceDescriptorType =
    ::MTL::AccelerationStructureInstanceDescriptorType;
inline constexpr auto AccelerationStructureInstanceDescriptorTypeDefault =
    ::MTL::AccelerationStructureInstanceDescriptorTypeDefault;
inline constexpr auto AccelerationStructureInstanceDescriptorTypeUserID =
    ::MTL::AccelerationStructureInstanceDescriptorTypeUserID;
inline constexpr auto AccelerationStructureInstanceDescriptorTypeMotion =
    ::MTL::AccelerationStructureInstanceDescriptorTypeMotion;
inline constexpr auto AccelerationStructureInstanceDescriptorTypeIndirect =
    ::MTL::AccelerationStructureInstanceDescriptorTypeIndirect;
inline constexpr auto AccelerationStructureInstanceDescriptorTypeIndirectMotion =
    ::MTL::AccelerationStructureInstanceDescriptorTypeIndirectMotion;
using TransformType = ::MTL::TransformType;
inline constexpr auto TransformTypePackedFloat4x3 = ::MTL::TransformTypePackedFloat4x3;
inline constexpr auto TransformTypeComponent = ::MTL::TransformTypeComponent;
using IndexType = ::MTL::IndexType;
inline constexpr auto IndexTypeUInt16 = ::MTL::IndexTypeUInt16;
inline constexpr auto IndexTypeUInt32 = ::MTL::IndexTypeUInt32;
using BindingType = ::MTL::BindingType;
inline constexpr auto BindingTypeBuffer = ::MTL::BindingTypeBuffer;
inline constexpr auto BindingTypeThreadgroupMemory = ::MTL::BindingTypeThreadgroupMemory;
inline constexpr auto BindingTypeTexture = ::MTL::BindingTypeTexture;
inline constexpr auto BindingTypeSampler = ::MTL::BindingTypeSampler;
inline constexpr auto BindingTypeImageblockData = ::MTL::BindingTypeImageblockData;
inline constexpr auto BindingTypeImageblock = ::MTL::BindingTypeImageblock;
inline constexpr auto BindingTypeVisibleFunctionTable = ::MTL::BindingTypeVisibleFunctionTable;
inline constexpr auto BindingTypePrimitiveAccelerationStructure =
    ::MTL::BindingTypePrimitiveAccelerationStructure;
inline constexpr auto BindingTypeInstanceAccelerationStructure =
    ::MTL::BindingTypeInstanceAccelerationStructure;
inline constexpr auto BindingTypeIntersectionFunctionTable =
    ::MTL::BindingTypeIntersectionFunctionTable;
inline constexpr auto BindingTypeObjectPayload = ::MTL::BindingTypeObjectPayload;
inline constexpr auto BindingTypeTensor = ::MTL::BindingTypeTensor;
using ArgumentType = ::MTL::ArgumentType;
inline constexpr auto ArgumentTypeBuffer = ::MTL::ArgumentTypeBuffer;
inline constexpr auto ArgumentTypeThreadgroupMemory = ::MTL::ArgumentTypeThreadgroupMemory;
inline constexpr auto ArgumentTypeTexture = ::MTL::ArgumentTypeTexture;
inline constexpr auto ArgumentTypeSampler = ::MTL::ArgumentTypeSampler;
inline constexpr auto ArgumentTypeImageblockData = ::MTL::ArgumentTypeImageblockData;
inline constexpr auto ArgumentTypeImageblock = ::MTL::ArgumentTypeImageblock;
inline constexpr auto ArgumentTypeVisibleFunctionTable = ::MTL::ArgumentTypeVisibleFunctionTable;
inline constexpr auto ArgumentTypePrimitiveAccelerationStructure =
    ::MTL::ArgumentTypePrimitiveAccelerationStructure;
inline constexpr auto ArgumentTypeInstanceAccelerationStructure =
    ::MTL::ArgumentTypeInstanceAccelerationStructure;
inline constexpr auto ArgumentTypeIntersectionFunctionTable =
    ::MTL::ArgumentTypeIntersectionFunctionTable;
using BindingAccess = ::MTL::BindingAccess;
inline constexpr auto BindingAccessReadOnly = ::MTL::BindingAccessReadOnly;
inline constexpr auto BindingAccessReadWrite = ::MTL::BindingAccessReadWrite;
inline constexpr auto BindingAccessWriteOnly = ::MTL::BindingAccessWriteOnly;
inline constexpr auto ArgumentAccessReadOnly = ::MTL::ArgumentAccessReadOnly;
inline constexpr auto ArgumentAccessReadWrite = ::MTL::ArgumentAccessReadWrite;
inline constexpr auto ArgumentAccessWriteOnly = ::MTL::ArgumentAccessWriteOnly;
using BinaryArchiveError = ::MTL::BinaryArchiveError;
inline constexpr auto BinaryArchiveErrorNone = ::MTL::BinaryArchiveErrorNone;
inline constexpr auto BinaryArchiveErrorInvalidFile = ::MTL::BinaryArchiveErrorInvalidFile;
inline constexpr auto BinaryArchiveErrorUnexpectedElement =
    ::MTL::BinaryArchiveErrorUnexpectedElement;
inline constexpr auto BinaryArchiveErrorCompilationFailure =
    ::MTL::BinaryArchiveErrorCompilationFailure;
inline constexpr auto BinaryArchiveErrorInternalError = ::MTL::BinaryArchiveErrorInternalError;
using CaptureError = ::MTL::CaptureError;
inline constexpr auto CaptureErrorNotSupported = ::MTL::CaptureErrorNotSupported;
inline constexpr auto CaptureErrorAlreadyCapturing = ::MTL::CaptureErrorAlreadyCapturing;
inline constexpr auto CaptureErrorInvalidDescriptor = ::MTL::CaptureErrorInvalidDescriptor;
using CaptureDestination = ::MTL::CaptureDestination;
inline constexpr auto CaptureDestinationDeveloperTools = ::MTL::CaptureDestinationDeveloperTools;
inline constexpr auto CaptureDestinationGPUTraceDocument =
    ::MTL::CaptureDestinationGPUTraceDocument;
using CommandBufferStatus = ::MTL::CommandBufferStatus;
inline constexpr auto CommandBufferStatusNotEnqueued = ::MTL::CommandBufferStatusNotEnqueued;
inline constexpr auto CommandBufferStatusEnqueued = ::MTL::CommandBufferStatusEnqueued;
inline constexpr auto CommandBufferStatusCommitted = ::MTL::CommandBufferStatusCommitted;
inline constexpr auto CommandBufferStatusScheduled = ::MTL::CommandBufferStatusScheduled;
inline constexpr auto CommandBufferStatusCompleted = ::MTL::CommandBufferStatusCompleted;
inline constexpr auto CommandBufferStatusError = ::MTL::CommandBufferStatusError;
using CommandBufferError = ::MTL::CommandBufferError;
inline constexpr auto CommandBufferErrorNone = ::MTL::CommandBufferErrorNone;
inline constexpr auto CommandBufferErrorInternal = ::MTL::CommandBufferErrorInternal;
inline constexpr auto CommandBufferErrorTimeout = ::MTL::CommandBufferErrorTimeout;
inline constexpr auto CommandBufferErrorPageFault = ::MTL::CommandBufferErrorPageFault;
inline constexpr auto CommandBufferErrorBlacklisted = ::MTL::CommandBufferErrorBlacklisted;
inline constexpr auto CommandBufferErrorAccessRevoked = ::MTL::CommandBufferErrorAccessRevoked;
inline constexpr auto CommandBufferErrorNotPermitted = ::MTL::CommandBufferErrorNotPermitted;
inline constexpr auto CommandBufferErrorOutOfMemory = ::MTL::CommandBufferErrorOutOfMemory;
inline constexpr auto CommandBufferErrorInvalidResource = ::MTL::CommandBufferErrorInvalidResource;
inline constexpr auto CommandBufferErrorMemoryless = ::MTL::CommandBufferErrorMemoryless;
inline constexpr auto CommandBufferErrorDeviceRemoved = ::MTL::CommandBufferErrorDeviceRemoved;
inline constexpr auto CommandBufferErrorStackOverflow = ::MTL::CommandBufferErrorStackOverflow;
using CommandEncoderErrorState = ::MTL::CommandEncoderErrorState;
inline constexpr auto CommandEncoderErrorStateUnknown = ::MTL::CommandEncoderErrorStateUnknown;
inline constexpr auto CommandEncoderErrorStateCompleted = ::MTL::CommandEncoderErrorStateCompleted;
inline constexpr auto CommandEncoderErrorStateAffected = ::MTL::CommandEncoderErrorStateAffected;
inline constexpr auto CommandEncoderErrorStatePending = ::MTL::CommandEncoderErrorStatePending;
inline constexpr auto CommandEncoderErrorStateFaulted = ::MTL::CommandEncoderErrorStateFaulted;
using DispatchType = ::MTL::DispatchType;
inline constexpr auto DispatchTypeSerial = ::MTL::DispatchTypeSerial;
inline constexpr auto DispatchTypeConcurrent = ::MTL::DispatchTypeConcurrent;
using CounterSampleBufferError = ::MTL::CounterSampleBufferError;
inline constexpr auto CounterSampleBufferErrorOutOfMemory =
    ::MTL::CounterSampleBufferErrorOutOfMemory;
inline constexpr auto CounterSampleBufferErrorInvalid = ::MTL::CounterSampleBufferErrorInvalid;
inline constexpr auto CounterSampleBufferErrorInternal = ::MTL::CounterSampleBufferErrorInternal;
using DataType = ::MTL::DataType;
inline constexpr auto DataTypeNone = ::MTL::DataTypeNone;
inline constexpr auto DataTypeStruct = ::MTL::DataTypeStruct;
inline constexpr auto DataTypeArray = ::MTL::DataTypeArray;
inline constexpr auto DataTypeFloat = ::MTL::DataTypeFloat;
inline constexpr auto DataTypeFloat2 = ::MTL::DataTypeFloat2;
inline constexpr auto DataTypeFloat3 = ::MTL::DataTypeFloat3;
inline constexpr auto DataTypeFloat4 = ::MTL::DataTypeFloat4;
inline constexpr auto DataTypeFloat2x2 = ::MTL::DataTypeFloat2x2;
inline constexpr auto DataTypeFloat2x3 = ::MTL::DataTypeFloat2x3;
inline constexpr auto DataTypeFloat2x4 = ::MTL::DataTypeFloat2x4;
inline constexpr auto DataTypeFloat3x2 = ::MTL::DataTypeFloat3x2;
inline constexpr auto DataTypeFloat3x3 = ::MTL::DataTypeFloat3x3;
inline constexpr auto DataTypeFloat3x4 = ::MTL::DataTypeFloat3x4;
inline constexpr auto DataTypeFloat4x2 = ::MTL::DataTypeFloat4x2;
inline constexpr auto DataTypeFloat4x3 = ::MTL::DataTypeFloat4x3;
inline constexpr auto DataTypeFloat4x4 = ::MTL::DataTypeFloat4x4;
inline constexpr auto DataTypeHalf = ::MTL::DataTypeHalf;
inline constexpr auto DataTypeHalf2 = ::MTL::DataTypeHalf2;
inline constexpr auto DataTypeHalf3 = ::MTL::DataTypeHalf3;
inline constexpr auto DataTypeHalf4 = ::MTL::DataTypeHalf4;
inline constexpr auto DataTypeHalf2x2 = ::MTL::DataTypeHalf2x2;
inline constexpr auto DataTypeHalf2x3 = ::MTL::DataTypeHalf2x3;
inline constexpr auto DataTypeHalf2x4 = ::MTL::DataTypeHalf2x4;
inline constexpr auto DataTypeHalf3x2 = ::MTL::DataTypeHalf3x2;
inline constexpr auto DataTypeHalf3x3 = ::MTL::DataTypeHalf3x3;
inline constexpr auto DataTypeHalf3x4 = ::MTL::DataTypeHalf3x4;
inline constexpr auto DataTypeHalf4x2 = ::MTL::DataTypeHalf4x2;
inline constexpr auto DataTypeHalf4x3 = ::MTL::DataTypeHalf4x3;
inline constexpr auto DataTypeHalf4x4 = ::MTL::DataTypeHalf4x4;
inline constexpr auto DataTypeInt = ::MTL::DataTypeInt;
inline constexpr auto DataTypeInt2 = ::MTL::DataTypeInt2;
inline constexpr auto DataTypeInt3 = ::MTL::DataTypeInt3;
inline constexpr auto DataTypeInt4 = ::MTL::DataTypeInt4;
inline constexpr auto DataTypeUInt = ::MTL::DataTypeUInt;
inline constexpr auto DataTypeUInt2 = ::MTL::DataTypeUInt2;
inline constexpr auto DataTypeUInt3 = ::MTL::DataTypeUInt3;
inline constexpr auto DataTypeUInt4 = ::MTL::DataTypeUInt4;
inline constexpr auto DataTypeShort = ::MTL::DataTypeShort;
inline constexpr auto DataTypeShort2 = ::MTL::DataTypeShort2;
inline constexpr auto DataTypeShort3 = ::MTL::DataTypeShort3;
inline constexpr auto DataTypeShort4 = ::MTL::DataTypeShort4;
inline constexpr auto DataTypeUShort = ::MTL::DataTypeUShort;
inline constexpr auto DataTypeUShort2 = ::MTL::DataTypeUShort2;
inline constexpr auto DataTypeUShort3 = ::MTL::DataTypeUShort3;
inline constexpr auto DataTypeUShort4 = ::MTL::DataTypeUShort4;
inline constexpr auto DataTypeChar = ::MTL::DataTypeChar;
inline constexpr auto DataTypeChar2 = ::MTL::DataTypeChar2;
inline constexpr auto DataTypeChar3 = ::MTL::DataTypeChar3;
inline constexpr auto DataTypeChar4 = ::MTL::DataTypeChar4;
inline constexpr auto DataTypeUChar = ::MTL::DataTypeUChar;
inline constexpr auto DataTypeUChar2 = ::MTL::DataTypeUChar2;
inline constexpr auto DataTypeUChar3 = ::MTL::DataTypeUChar3;
inline constexpr auto DataTypeUChar4 = ::MTL::DataTypeUChar4;
inline constexpr auto DataTypeBool = ::MTL::DataTypeBool;
inline constexpr auto DataTypeBool2 = ::MTL::DataTypeBool2;
inline constexpr auto DataTypeBool3 = ::MTL::DataTypeBool3;
inline constexpr auto DataTypeBool4 = ::MTL::DataTypeBool4;
inline constexpr auto DataTypeTexture = ::MTL::DataTypeTexture;
inline constexpr auto DataTypeSampler = ::MTL::DataTypeSampler;
inline constexpr auto DataTypePointer = ::MTL::DataTypePointer;
inline constexpr auto DataTypeR8Unorm = ::MTL::DataTypeR8Unorm;
inline constexpr auto DataTypeR8Snorm = ::MTL::DataTypeR8Snorm;
inline constexpr auto DataTypeR16Unorm = ::MTL::DataTypeR16Unorm;
inline constexpr auto DataTypeR16Snorm = ::MTL::DataTypeR16Snorm;
inline constexpr auto DataTypeRG8Unorm = ::MTL::DataTypeRG8Unorm;
inline constexpr auto DataTypeRG8Snorm = ::MTL::DataTypeRG8Snorm;
inline constexpr auto DataTypeRG16Unorm = ::MTL::DataTypeRG16Unorm;
inline constexpr auto DataTypeRG16Snorm = ::MTL::DataTypeRG16Snorm;
inline constexpr auto DataTypeRGBA8Unorm = ::MTL::DataTypeRGBA8Unorm;
inline constexpr auto DataTypeRGBA8Unorm_sRGB = ::MTL::DataTypeRGBA8Unorm_sRGB;
inline constexpr auto DataTypeRGBA8Snorm = ::MTL::DataTypeRGBA8Snorm;
inline constexpr auto DataTypeRGBA16Unorm = ::MTL::DataTypeRGBA16Unorm;
inline constexpr auto DataTypeRGBA16Snorm = ::MTL::DataTypeRGBA16Snorm;
inline constexpr auto DataTypeRGB10A2Unorm = ::MTL::DataTypeRGB10A2Unorm;
inline constexpr auto DataTypeRG11B10Float = ::MTL::DataTypeRG11B10Float;
inline constexpr auto DataTypeRGB9E5Float = ::MTL::DataTypeRGB9E5Float;
inline constexpr auto DataTypeRenderPipeline = ::MTL::DataTypeRenderPipeline;
inline constexpr auto DataTypeComputePipeline = ::MTL::DataTypeComputePipeline;
inline constexpr auto DataTypeIndirectCommandBuffer = ::MTL::DataTypeIndirectCommandBuffer;
inline constexpr auto DataTypeLong = ::MTL::DataTypeLong;
inline constexpr auto DataTypeLong2 = ::MTL::DataTypeLong2;
inline constexpr auto DataTypeLong3 = ::MTL::DataTypeLong3;
inline constexpr auto DataTypeLong4 = ::MTL::DataTypeLong4;
inline constexpr auto DataTypeULong = ::MTL::DataTypeULong;
inline constexpr auto DataTypeULong2 = ::MTL::DataTypeULong2;
inline constexpr auto DataTypeULong3 = ::MTL::DataTypeULong3;
inline constexpr auto DataTypeULong4 = ::MTL::DataTypeULong4;
inline constexpr auto DataTypeVisibleFunctionTable = ::MTL::DataTypeVisibleFunctionTable;
inline constexpr auto DataTypeIntersectionFunctionTable = ::MTL::DataTypeIntersectionFunctionTable;
inline constexpr auto DataTypePrimitiveAccelerationStructure =
    ::MTL::DataTypePrimitiveAccelerationStructure;
inline constexpr auto DataTypeInstanceAccelerationStructure =
    ::MTL::DataTypeInstanceAccelerationStructure;
inline constexpr auto DataTypeBFloat = ::MTL::DataTypeBFloat;
inline constexpr auto DataTypeBFloat2 = ::MTL::DataTypeBFloat2;
inline constexpr auto DataTypeBFloat3 = ::MTL::DataTypeBFloat3;
inline constexpr auto DataTypeBFloat4 = ::MTL::DataTypeBFloat4;
inline constexpr auto DataTypeDepthStencilState = ::MTL::DataTypeDepthStencilState;
inline constexpr auto DataTypeTensor = ::MTL::DataTypeTensor;
using CompareFunction = ::MTL::CompareFunction;
inline constexpr auto CompareFunctionNever = ::MTL::CompareFunctionNever;
inline constexpr auto CompareFunctionLess = ::MTL::CompareFunctionLess;
inline constexpr auto CompareFunctionEqual = ::MTL::CompareFunctionEqual;
inline constexpr auto CompareFunctionLessEqual = ::MTL::CompareFunctionLessEqual;
inline constexpr auto CompareFunctionGreater = ::MTL::CompareFunctionGreater;
inline constexpr auto CompareFunctionNotEqual = ::MTL::CompareFunctionNotEqual;
inline constexpr auto CompareFunctionGreaterEqual = ::MTL::CompareFunctionGreaterEqual;
inline constexpr auto CompareFunctionAlways = ::MTL::CompareFunctionAlways;
using StencilOperation = ::MTL::StencilOperation;
inline constexpr auto StencilOperationKeep = ::MTL::StencilOperationKeep;
inline constexpr auto StencilOperationZero = ::MTL::StencilOperationZero;
inline constexpr auto StencilOperationReplace = ::MTL::StencilOperationReplace;
inline constexpr auto StencilOperationIncrementClamp = ::MTL::StencilOperationIncrementClamp;
inline constexpr auto StencilOperationDecrementClamp = ::MTL::StencilOperationDecrementClamp;
inline constexpr auto StencilOperationInvert = ::MTL::StencilOperationInvert;
inline constexpr auto StencilOperationIncrementWrap = ::MTL::StencilOperationIncrementWrap;
inline constexpr auto StencilOperationDecrementWrap = ::MTL::StencilOperationDecrementWrap;
using IOCompressionMethod = ::MTL::IOCompressionMethod;
inline constexpr auto IOCompressionMethodZlib = ::MTL::IOCompressionMethodZlib;
inline constexpr auto IOCompressionMethodLZFSE = ::MTL::IOCompressionMethodLZFSE;
inline constexpr auto IOCompressionMethodLZ4 = ::MTL::IOCompressionMethodLZ4;
inline constexpr auto IOCompressionMethodLZMA = ::MTL::IOCompressionMethodLZMA;
inline constexpr auto IOCompressionMethodLZBitmap = ::MTL::IOCompressionMethodLZBitmap;
using FeatureSet = ::MTL::FeatureSet;
inline constexpr auto FeatureSet_iOS_GPUFamily1_v1 = ::MTL::FeatureSet_iOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_iOS_GPUFamily2_v1 = ::MTL::FeatureSet_iOS_GPUFamily2_v1;
inline constexpr auto FeatureSet_iOS_GPUFamily1_v2 = ::MTL::FeatureSet_iOS_GPUFamily1_v2;
inline constexpr auto FeatureSet_iOS_GPUFamily2_v2 = ::MTL::FeatureSet_iOS_GPUFamily2_v2;
inline constexpr auto FeatureSet_iOS_GPUFamily3_v1 = ::MTL::FeatureSet_iOS_GPUFamily3_v1;
inline constexpr auto FeatureSet_iOS_GPUFamily1_v3 = ::MTL::FeatureSet_iOS_GPUFamily1_v3;
inline constexpr auto FeatureSet_iOS_GPUFamily2_v3 = ::MTL::FeatureSet_iOS_GPUFamily2_v3;
inline constexpr auto FeatureSet_iOS_GPUFamily3_v2 = ::MTL::FeatureSet_iOS_GPUFamily3_v2;
inline constexpr auto FeatureSet_iOS_GPUFamily1_v4 = ::MTL::FeatureSet_iOS_GPUFamily1_v4;
inline constexpr auto FeatureSet_iOS_GPUFamily2_v4 = ::MTL::FeatureSet_iOS_GPUFamily2_v4;
inline constexpr auto FeatureSet_iOS_GPUFamily3_v3 = ::MTL::FeatureSet_iOS_GPUFamily3_v3;
inline constexpr auto FeatureSet_iOS_GPUFamily4_v1 = ::MTL::FeatureSet_iOS_GPUFamily4_v1;
inline constexpr auto FeatureSet_iOS_GPUFamily1_v5 = ::MTL::FeatureSet_iOS_GPUFamily1_v5;
inline constexpr auto FeatureSet_iOS_GPUFamily2_v5 = ::MTL::FeatureSet_iOS_GPUFamily2_v5;
inline constexpr auto FeatureSet_iOS_GPUFamily3_v4 = ::MTL::FeatureSet_iOS_GPUFamily3_v4;
inline constexpr auto FeatureSet_iOS_GPUFamily4_v2 = ::MTL::FeatureSet_iOS_GPUFamily4_v2;
inline constexpr auto FeatureSet_iOS_GPUFamily5_v1 = ::MTL::FeatureSet_iOS_GPUFamily5_v1;
inline constexpr auto FeatureSet_macOS_GPUFamily1_v1 = ::MTL::FeatureSet_macOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_OSX_GPUFamily1_v1 = ::MTL::FeatureSet_OSX_GPUFamily1_v1;
inline constexpr auto FeatureSet_macOS_GPUFamily1_v2 = ::MTL::FeatureSet_macOS_GPUFamily1_v2;
inline constexpr auto FeatureSet_OSX_GPUFamily1_v2 = ::MTL::FeatureSet_OSX_GPUFamily1_v2;
inline constexpr auto FeatureSet_macOS_ReadWriteTextureTier2 =
    ::MTL::FeatureSet_macOS_ReadWriteTextureTier2;
inline constexpr auto FeatureSet_OSX_ReadWriteTextureTier2 =
    ::MTL::FeatureSet_OSX_ReadWriteTextureTier2;
inline constexpr auto FeatureSet_macOS_GPUFamily1_v3 = ::MTL::FeatureSet_macOS_GPUFamily1_v3;
inline constexpr auto FeatureSet_macOS_GPUFamily1_v4 = ::MTL::FeatureSet_macOS_GPUFamily1_v4;
inline constexpr auto FeatureSet_macOS_GPUFamily2_v1 = ::MTL::FeatureSet_macOS_GPUFamily2_v1;
inline constexpr auto FeatureSet_watchOS_GPUFamily1_v1 = ::MTL::FeatureSet_watchOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_WatchOS_GPUFamily1_v1 = ::MTL::FeatureSet_WatchOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_watchOS_GPUFamily2_v1 = ::MTL::FeatureSet_watchOS_GPUFamily2_v1;
inline constexpr auto FeatureSet_WatchOS_GPUFamily2_v1 = ::MTL::FeatureSet_WatchOS_GPUFamily2_v1;
inline constexpr auto FeatureSet_tvOS_GPUFamily1_v1 = ::MTL::FeatureSet_tvOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_TVOS_GPUFamily1_v1 = ::MTL::FeatureSet_TVOS_GPUFamily1_v1;
inline constexpr auto FeatureSet_tvOS_GPUFamily1_v2 = ::MTL::FeatureSet_tvOS_GPUFamily1_v2;
inline constexpr auto FeatureSet_tvOS_GPUFamily1_v3 = ::MTL::FeatureSet_tvOS_GPUFamily1_v3;
inline constexpr auto FeatureSet_tvOS_GPUFamily2_v1 = ::MTL::FeatureSet_tvOS_GPUFamily2_v1;
inline constexpr auto FeatureSet_tvOS_GPUFamily1_v4 = ::MTL::FeatureSet_tvOS_GPUFamily1_v4;
inline constexpr auto FeatureSet_tvOS_GPUFamily2_v2 = ::MTL::FeatureSet_tvOS_GPUFamily2_v2;
using GPUFamily = ::MTL::GPUFamily;
inline constexpr auto GPUFamilyApple1 = ::MTL::GPUFamilyApple1;
inline constexpr auto GPUFamilyApple2 = ::MTL::GPUFamilyApple2;
inline constexpr auto GPUFamilyApple3 = ::MTL::GPUFamilyApple3;
inline constexpr auto GPUFamilyApple4 = ::MTL::GPUFamilyApple4;
inline constexpr auto GPUFamilyApple5 = ::MTL::GPUFamilyApple5;
inline constexpr auto GPUFamilyApple6 = ::MTL::GPUFamilyApple6;
inline constexpr auto GPUFamilyApple7 = ::MTL::GPUFamilyApple7;
inline constexpr auto GPUFamilyApple8 = ::MTL::GPUFamilyApple8;
inline constexpr auto GPUFamilyApple9 = ::MTL::GPUFamilyApple9;
inline constexpr auto GPUFamilyApple10 = ::MTL::GPUFamilyApple10;
inline constexpr auto GPUFamilyMac1 = ::MTL::GPUFamilyMac1;
inline constexpr auto GPUFamilyMac2 = ::MTL::GPUFamilyMac2;
inline constexpr auto GPUFamilyCommon1 = ::MTL::GPUFamilyCommon1;
inline constexpr auto GPUFamilyCommon2 = ::MTL::GPUFamilyCommon2;
inline constexpr auto GPUFamilyCommon3 = ::MTL::GPUFamilyCommon3;
inline constexpr auto GPUFamilyMacCatalyst1 = ::MTL::GPUFamilyMacCatalyst1;
inline constexpr auto GPUFamilyMacCatalyst2 = ::MTL::GPUFamilyMacCatalyst2;
inline constexpr auto GPUFamilyMetal3 = ::MTL::GPUFamilyMetal3;
inline constexpr auto GPUFamilyMetal4 = ::MTL::GPUFamilyMetal4;
using DeviceLocation = ::MTL::DeviceLocation;
inline constexpr auto DeviceLocationBuiltIn = ::MTL::DeviceLocationBuiltIn;
inline constexpr auto DeviceLocationSlot = ::MTL::DeviceLocationSlot;
inline constexpr auto DeviceLocationExternal = ::MTL::DeviceLocationExternal;
inline constexpr auto DeviceLocationUnspecified = ::MTL::DeviceLocationUnspecified;
using ReadWriteTextureTier = ::MTL::ReadWriteTextureTier;
inline constexpr auto ReadWriteTextureTierNone = ::MTL::ReadWriteTextureTierNone;
inline constexpr auto ReadWriteTextureTier1 = ::MTL::ReadWriteTextureTier1;
inline constexpr auto ReadWriteTextureTier2 = ::MTL::ReadWriteTextureTier2;
using ArgumentBuffersTier = ::MTL::ArgumentBuffersTier;
inline constexpr auto ArgumentBuffersTier1 = ::MTL::ArgumentBuffersTier1;
inline constexpr auto ArgumentBuffersTier2 = ::MTL::ArgumentBuffersTier2;
using SparseTextureRegionAlignmentMode = ::MTL::SparseTextureRegionAlignmentMode;
inline constexpr auto SparseTextureRegionAlignmentModeOutward =
    ::MTL::SparseTextureRegionAlignmentModeOutward;
inline constexpr auto SparseTextureRegionAlignmentModeInward =
    ::MTL::SparseTextureRegionAlignmentModeInward;
using CounterSamplingPoint = ::MTL::CounterSamplingPoint;
inline constexpr auto CounterSamplingPointAtStageBoundary =
    ::MTL::CounterSamplingPointAtStageBoundary;
inline constexpr auto CounterSamplingPointAtDrawBoundary =
    ::MTL::CounterSamplingPointAtDrawBoundary;
inline constexpr auto CounterSamplingPointAtDispatchBoundary =
    ::MTL::CounterSamplingPointAtDispatchBoundary;
inline constexpr auto CounterSamplingPointAtTileDispatchBoundary =
    ::MTL::CounterSamplingPointAtTileDispatchBoundary;
inline constexpr auto CounterSamplingPointAtBlitBoundary =
    ::MTL::CounterSamplingPointAtBlitBoundary;
using DeviceError = ::MTL::DeviceError;
inline constexpr auto DeviceErrorNone = ::MTL::DeviceErrorNone;
inline constexpr auto DeviceErrorNotSupported = ::MTL::DeviceErrorNotSupported;
using DynamicLibraryError = ::MTL::DynamicLibraryError;
inline constexpr auto DynamicLibraryErrorNone = ::MTL::DynamicLibraryErrorNone;
inline constexpr auto DynamicLibraryErrorInvalidFile = ::MTL::DynamicLibraryErrorInvalidFile;
inline constexpr auto DynamicLibraryErrorCompilationFailure =
    ::MTL::DynamicLibraryErrorCompilationFailure;
inline constexpr auto DynamicLibraryErrorUnresolvedInstallName =
    ::MTL::DynamicLibraryErrorUnresolvedInstallName;
inline constexpr auto DynamicLibraryErrorDependencyLoadFailure =
    ::MTL::DynamicLibraryErrorDependencyLoadFailure;
inline constexpr auto DynamicLibraryErrorUnsupported = ::MTL::DynamicLibraryErrorUnsupported;
using FunctionLogType = ::MTL::FunctionLogType;
inline constexpr auto FunctionLogTypeValidation = ::MTL::FunctionLogTypeValidation;
using HeapType = ::MTL::HeapType;
inline constexpr auto HeapTypeAutomatic = ::MTL::HeapTypeAutomatic;
inline constexpr auto HeapTypePlacement = ::MTL::HeapTypePlacement;
inline constexpr auto HeapTypeSparse = ::MTL::HeapTypeSparse;
using IOStatus = ::MTL::IOStatus;
inline constexpr auto IOStatusPending = ::MTL::IOStatusPending;
inline constexpr auto IOStatusCancelled = ::MTL::IOStatusCancelled;
inline constexpr auto IOStatusError = ::MTL::IOStatusError;
inline constexpr auto IOStatusComplete = ::MTL::IOStatusComplete;
using IOPriority = ::MTL::IOPriority;
inline constexpr auto IOPriorityHigh = ::MTL::IOPriorityHigh;
inline constexpr auto IOPriorityNormal = ::MTL::IOPriorityNormal;
inline constexpr auto IOPriorityLow = ::MTL::IOPriorityLow;
using IOCommandQueueType = ::MTL::IOCommandQueueType;
inline constexpr auto IOCommandQueueTypeConcurrent = ::MTL::IOCommandQueueTypeConcurrent;
inline constexpr auto IOCommandQueueTypeSerial = ::MTL::IOCommandQueueTypeSerial;
using IOError = ::MTL::IOError;
inline constexpr auto IOErrorURLInvalid = ::MTL::IOErrorURLInvalid;
inline constexpr auto IOErrorInternal = ::MTL::IOErrorInternal;
using IOCompressionStatus = ::MTL::IOCompressionStatus;
inline constexpr auto IOCompressionStatusComplete = ::MTL::IOCompressionStatusComplete;
inline constexpr auto IOCompressionStatusError = ::MTL::IOCompressionStatusError;
using PatchType = ::MTL::PatchType;
inline constexpr auto PatchTypeNone = ::MTL::PatchTypeNone;
inline constexpr auto PatchTypeTriangle = ::MTL::PatchTypeTriangle;
inline constexpr auto PatchTypeQuad = ::MTL::PatchTypeQuad;
using FunctionType = ::MTL::FunctionType;
inline constexpr auto FunctionTypeVertex = ::MTL::FunctionTypeVertex;
inline constexpr auto FunctionTypeFragment = ::MTL::FunctionTypeFragment;
inline constexpr auto FunctionTypeKernel = ::MTL::FunctionTypeKernel;
inline constexpr auto FunctionTypeVisible = ::MTL::FunctionTypeVisible;
inline constexpr auto FunctionTypeIntersection = ::MTL::FunctionTypeIntersection;
inline constexpr auto FunctionTypeMesh = ::MTL::FunctionTypeMesh;
inline constexpr auto FunctionTypeObject = ::MTL::FunctionTypeObject;
using LanguageVersion = ::MTL::LanguageVersion;
inline constexpr auto LanguageVersion1_0 = ::MTL::LanguageVersion1_0;
inline constexpr auto LanguageVersion1_1 = ::MTL::LanguageVersion1_1;
inline constexpr auto LanguageVersion1_2 = ::MTL::LanguageVersion1_2;
inline constexpr auto LanguageVersion2_0 = ::MTL::LanguageVersion2_0;
inline constexpr auto LanguageVersion2_1 = ::MTL::LanguageVersion2_1;
inline constexpr auto LanguageVersion2_2 = ::MTL::LanguageVersion2_2;
inline constexpr auto LanguageVersion2_3 = ::MTL::LanguageVersion2_3;
inline constexpr auto LanguageVersion2_4 = ::MTL::LanguageVersion2_4;
inline constexpr auto LanguageVersion3_0 = ::MTL::LanguageVersion3_0;
inline constexpr auto LanguageVersion3_1 = ::MTL::LanguageVersion3_1;
inline constexpr auto LanguageVersion3_2 = ::MTL::LanguageVersion3_2;
inline constexpr auto LanguageVersion4_0 = ::MTL::LanguageVersion4_0;
inline constexpr auto LanguageVersion4_1 = ::MTL::LanguageVersion4_1;
using LibraryType = ::MTL::LibraryType;
inline constexpr auto LibraryTypeExecutable = ::MTL::LibraryTypeExecutable;
inline constexpr auto LibraryTypeDynamic = ::MTL::LibraryTypeDynamic;
using LibraryOptimizationLevel = ::MTL::LibraryOptimizationLevel;
inline constexpr auto LibraryOptimizationLevelDefault = ::MTL::LibraryOptimizationLevelDefault;
inline constexpr auto LibraryOptimizationLevelSize = ::MTL::LibraryOptimizationLevelSize;
using CompileSymbolVisibility = ::MTL::CompileSymbolVisibility;
inline constexpr auto CompileSymbolVisibilityDefault = ::MTL::CompileSymbolVisibilityDefault;
inline constexpr auto CompileSymbolVisibilityHidden = ::MTL::CompileSymbolVisibilityHidden;
using MathMode = ::MTL::MathMode;
inline constexpr auto MathModeSafe = ::MTL::MathModeSafe;
inline constexpr auto MathModeRelaxed = ::MTL::MathModeRelaxed;
inline constexpr auto MathModeFast = ::MTL::MathModeFast;
using MathFloatingPointFunctions = ::MTL::MathFloatingPointFunctions;
inline constexpr auto MathFloatingPointFunctionsFast = ::MTL::MathFloatingPointFunctionsFast;
inline constexpr auto MathFloatingPointFunctionsPrecise = ::MTL::MathFloatingPointFunctionsPrecise;
using FloatingPointConversionRoundingMode = ::MTL::FloatingPointConversionRoundingMode;
inline constexpr auto FloatingPointConversionRoundingModeToNearestEven =
    ::MTL::FloatingPointConversionRoundingModeToNearestEven;
inline constexpr auto FloatingPointConversionRoundingModeTowardZero =
    ::MTL::FloatingPointConversionRoundingModeTowardZero;
using LibraryError = ::MTL::LibraryError;
inline constexpr auto LibraryErrorUnsupported = ::MTL::LibraryErrorUnsupported;
inline constexpr auto LibraryErrorInternal = ::MTL::LibraryErrorInternal;
inline constexpr auto LibraryErrorCompileFailure = ::MTL::LibraryErrorCompileFailure;
inline constexpr auto LibraryErrorCompileWarning = ::MTL::LibraryErrorCompileWarning;
inline constexpr auto LibraryErrorFunctionNotFound = ::MTL::LibraryErrorFunctionNotFound;
inline constexpr auto LibraryErrorFileNotFound = ::MTL::LibraryErrorFileNotFound;
using LogLevel = ::MTL::LogLevel;
inline constexpr auto LogLevelUndefined = ::MTL::LogLevelUndefined;
inline constexpr auto LogLevelDebug = ::MTL::LogLevelDebug;
inline constexpr auto LogLevelInfo = ::MTL::LogLevelInfo;
inline constexpr auto LogLevelNotice = ::MTL::LogLevelNotice;
inline constexpr auto LogLevelError = ::MTL::LogLevelError;
inline constexpr auto LogLevelFault = ::MTL::LogLevelFault;
using LogStateError = ::MTL::LogStateError;
inline constexpr auto LogStateErrorInvalidSize = ::MTL::LogStateErrorInvalidSize;
inline constexpr auto LogStateErrorInvalid = ::MTL::LogStateErrorInvalid;
using Mutability = ::MTL::Mutability;
inline constexpr auto MutabilityDefault = ::MTL::MutabilityDefault;
inline constexpr auto MutabilityMutable = ::MTL::MutabilityMutable;
inline constexpr auto MutabilityImmutable = ::MTL::MutabilityImmutable;
using ShaderValidation = ::MTL::ShaderValidation;
inline constexpr auto ShaderValidationDefault = ::MTL::ShaderValidationDefault;
inline constexpr auto ShaderValidationEnabled = ::MTL::ShaderValidationEnabled;
inline constexpr auto ShaderValidationDisabled = ::MTL::ShaderValidationDisabled;
using PixelFormat = ::MTL::PixelFormat;
inline constexpr auto PixelFormatInvalid = ::MTL::PixelFormatInvalid;
inline constexpr auto PixelFormatA8Unorm = ::MTL::PixelFormatA8Unorm;
inline constexpr auto PixelFormatR8Unorm = ::MTL::PixelFormatR8Unorm;
inline constexpr auto PixelFormatR8Unorm_sRGB = ::MTL::PixelFormatR8Unorm_sRGB;
inline constexpr auto PixelFormatR8Snorm = ::MTL::PixelFormatR8Snorm;
inline constexpr auto PixelFormatR8Uint = ::MTL::PixelFormatR8Uint;
inline constexpr auto PixelFormatR8Sint = ::MTL::PixelFormatR8Sint;
inline constexpr auto PixelFormatR16Unorm = ::MTL::PixelFormatR16Unorm;
inline constexpr auto PixelFormatR16Snorm = ::MTL::PixelFormatR16Snorm;
inline constexpr auto PixelFormatR16Uint = ::MTL::PixelFormatR16Uint;
inline constexpr auto PixelFormatR16Sint = ::MTL::PixelFormatR16Sint;
inline constexpr auto PixelFormatR16Float = ::MTL::PixelFormatR16Float;
inline constexpr auto PixelFormatRG8Unorm = ::MTL::PixelFormatRG8Unorm;
inline constexpr auto PixelFormatRG8Unorm_sRGB = ::MTL::PixelFormatRG8Unorm_sRGB;
inline constexpr auto PixelFormatRG8Snorm = ::MTL::PixelFormatRG8Snorm;
inline constexpr auto PixelFormatRG8Uint = ::MTL::PixelFormatRG8Uint;
inline constexpr auto PixelFormatRG8Sint = ::MTL::PixelFormatRG8Sint;
inline constexpr auto PixelFormatB5G6R5Unorm = ::MTL::PixelFormatB5G6R5Unorm;
inline constexpr auto PixelFormatA1BGR5Unorm = ::MTL::PixelFormatA1BGR5Unorm;
inline constexpr auto PixelFormatABGR4Unorm = ::MTL::PixelFormatABGR4Unorm;
inline constexpr auto PixelFormatBGR5A1Unorm = ::MTL::PixelFormatBGR5A1Unorm;
inline constexpr auto PixelFormatR32Uint = ::MTL::PixelFormatR32Uint;
inline constexpr auto PixelFormatR32Sint = ::MTL::PixelFormatR32Sint;
inline constexpr auto PixelFormatR32Float = ::MTL::PixelFormatR32Float;
inline constexpr auto PixelFormatRG16Unorm = ::MTL::PixelFormatRG16Unorm;
inline constexpr auto PixelFormatRG16Snorm = ::MTL::PixelFormatRG16Snorm;
inline constexpr auto PixelFormatRG16Uint = ::MTL::PixelFormatRG16Uint;
inline constexpr auto PixelFormatRG16Sint = ::MTL::PixelFormatRG16Sint;
inline constexpr auto PixelFormatRG16Float = ::MTL::PixelFormatRG16Float;
inline constexpr auto PixelFormatRGBA8Unorm = ::MTL::PixelFormatRGBA8Unorm;
inline constexpr auto PixelFormatRGBA8Unorm_sRGB = ::MTL::PixelFormatRGBA8Unorm_sRGB;
inline constexpr auto PixelFormatRGBA8Snorm = ::MTL::PixelFormatRGBA8Snorm;
inline constexpr auto PixelFormatRGBA8Uint = ::MTL::PixelFormatRGBA8Uint;
inline constexpr auto PixelFormatRGBA8Sint = ::MTL::PixelFormatRGBA8Sint;
inline constexpr auto PixelFormatBGRA8Unorm = ::MTL::PixelFormatBGRA8Unorm;
inline constexpr auto PixelFormatBGRA8Unorm_sRGB = ::MTL::PixelFormatBGRA8Unorm_sRGB;
inline constexpr auto PixelFormatRGB10A2Unorm = ::MTL::PixelFormatRGB10A2Unorm;
inline constexpr auto PixelFormatRGB10A2Uint = ::MTL::PixelFormatRGB10A2Uint;
inline constexpr auto PixelFormatRG11B10Float = ::MTL::PixelFormatRG11B10Float;
inline constexpr auto PixelFormatRGB9E5Float = ::MTL::PixelFormatRGB9E5Float;
inline constexpr auto PixelFormatBGR10A2Unorm = ::MTL::PixelFormatBGR10A2Unorm;
inline constexpr auto PixelFormatBGR10_XR = ::MTL::PixelFormatBGR10_XR;
inline constexpr auto PixelFormatBGR10_XR_sRGB = ::MTL::PixelFormatBGR10_XR_sRGB;
inline constexpr auto PixelFormatRG32Uint = ::MTL::PixelFormatRG32Uint;
inline constexpr auto PixelFormatRG32Sint = ::MTL::PixelFormatRG32Sint;
inline constexpr auto PixelFormatRG32Float = ::MTL::PixelFormatRG32Float;
inline constexpr auto PixelFormatRGBA16Unorm = ::MTL::PixelFormatRGBA16Unorm;
inline constexpr auto PixelFormatRGBA16Snorm = ::MTL::PixelFormatRGBA16Snorm;
inline constexpr auto PixelFormatRGBA16Uint = ::MTL::PixelFormatRGBA16Uint;
inline constexpr auto PixelFormatRGBA16Sint = ::MTL::PixelFormatRGBA16Sint;
inline constexpr auto PixelFormatRGBA16Float = ::MTL::PixelFormatRGBA16Float;
inline constexpr auto PixelFormatBGRA10_XR = ::MTL::PixelFormatBGRA10_XR;
inline constexpr auto PixelFormatBGRA10_XR_sRGB = ::MTL::PixelFormatBGRA10_XR_sRGB;
inline constexpr auto PixelFormatRGBA32Uint = ::MTL::PixelFormatRGBA32Uint;
inline constexpr auto PixelFormatRGBA32Sint = ::MTL::PixelFormatRGBA32Sint;
inline constexpr auto PixelFormatRGBA32Float = ::MTL::PixelFormatRGBA32Float;
inline constexpr auto PixelFormatBC1_RGBA = ::MTL::PixelFormatBC1_RGBA;
inline constexpr auto PixelFormatBC1_RGBA_sRGB = ::MTL::PixelFormatBC1_RGBA_sRGB;
inline constexpr auto PixelFormatBC2_RGBA = ::MTL::PixelFormatBC2_RGBA;
inline constexpr auto PixelFormatBC2_RGBA_sRGB = ::MTL::PixelFormatBC2_RGBA_sRGB;
inline constexpr auto PixelFormatBC3_RGBA = ::MTL::PixelFormatBC3_RGBA;
inline constexpr auto PixelFormatBC3_RGBA_sRGB = ::MTL::PixelFormatBC3_RGBA_sRGB;
inline constexpr auto PixelFormatBC4_RUnorm = ::MTL::PixelFormatBC4_RUnorm;
inline constexpr auto PixelFormatBC4_RSnorm = ::MTL::PixelFormatBC4_RSnorm;
inline constexpr auto PixelFormatBC5_RGUnorm = ::MTL::PixelFormatBC5_RGUnorm;
inline constexpr auto PixelFormatBC5_RGSnorm = ::MTL::PixelFormatBC5_RGSnorm;
inline constexpr auto PixelFormatBC6H_RGBFloat = ::MTL::PixelFormatBC6H_RGBFloat;
inline constexpr auto PixelFormatBC6H_RGBUfloat = ::MTL::PixelFormatBC6H_RGBUfloat;
inline constexpr auto PixelFormatBC7_RGBAUnorm = ::MTL::PixelFormatBC7_RGBAUnorm;
inline constexpr auto PixelFormatBC7_RGBAUnorm_sRGB = ::MTL::PixelFormatBC7_RGBAUnorm_sRGB;
inline constexpr auto PixelFormatPVRTC_RGB_2BPP = ::MTL::PixelFormatPVRTC_RGB_2BPP;
inline constexpr auto PixelFormatPVRTC_RGB_2BPP_sRGB = ::MTL::PixelFormatPVRTC_RGB_2BPP_sRGB;
inline constexpr auto PixelFormatPVRTC_RGB_4BPP = ::MTL::PixelFormatPVRTC_RGB_4BPP;
inline constexpr auto PixelFormatPVRTC_RGB_4BPP_sRGB = ::MTL::PixelFormatPVRTC_RGB_4BPP_sRGB;
inline constexpr auto PixelFormatPVRTC_RGBA_2BPP = ::MTL::PixelFormatPVRTC_RGBA_2BPP;
inline constexpr auto PixelFormatPVRTC_RGBA_2BPP_sRGB = ::MTL::PixelFormatPVRTC_RGBA_2BPP_sRGB;
inline constexpr auto PixelFormatPVRTC_RGBA_4BPP = ::MTL::PixelFormatPVRTC_RGBA_4BPP;
inline constexpr auto PixelFormatPVRTC_RGBA_4BPP_sRGB = ::MTL::PixelFormatPVRTC_RGBA_4BPP_sRGB;
inline constexpr auto PixelFormatEAC_R11Unorm = ::MTL::PixelFormatEAC_R11Unorm;
inline constexpr auto PixelFormatEAC_R11Snorm = ::MTL::PixelFormatEAC_R11Snorm;
inline constexpr auto PixelFormatEAC_RG11Unorm = ::MTL::PixelFormatEAC_RG11Unorm;
inline constexpr auto PixelFormatEAC_RG11Snorm = ::MTL::PixelFormatEAC_RG11Snorm;
inline constexpr auto PixelFormatEAC_RGBA8 = ::MTL::PixelFormatEAC_RGBA8;
inline constexpr auto PixelFormatEAC_RGBA8_sRGB = ::MTL::PixelFormatEAC_RGBA8_sRGB;
inline constexpr auto PixelFormatETC2_RGB8 = ::MTL::PixelFormatETC2_RGB8;
inline constexpr auto PixelFormatETC2_RGB8_sRGB = ::MTL::PixelFormatETC2_RGB8_sRGB;
inline constexpr auto PixelFormatETC2_RGB8A1 = ::MTL::PixelFormatETC2_RGB8A1;
inline constexpr auto PixelFormatETC2_RGB8A1_sRGB = ::MTL::PixelFormatETC2_RGB8A1_sRGB;
inline constexpr auto PixelFormatASTC_4x4_sRGB = ::MTL::PixelFormatASTC_4x4_sRGB;
inline constexpr auto PixelFormatASTC_5x4_sRGB = ::MTL::PixelFormatASTC_5x4_sRGB;
inline constexpr auto PixelFormatASTC_5x5_sRGB = ::MTL::PixelFormatASTC_5x5_sRGB;
inline constexpr auto PixelFormatASTC_6x5_sRGB = ::MTL::PixelFormatASTC_6x5_sRGB;
inline constexpr auto PixelFormatASTC_6x6_sRGB = ::MTL::PixelFormatASTC_6x6_sRGB;
inline constexpr auto PixelFormatASTC_8x5_sRGB = ::MTL::PixelFormatASTC_8x5_sRGB;
inline constexpr auto PixelFormatASTC_8x6_sRGB = ::MTL::PixelFormatASTC_8x6_sRGB;
inline constexpr auto PixelFormatASTC_8x8_sRGB = ::MTL::PixelFormatASTC_8x8_sRGB;
inline constexpr auto PixelFormatASTC_10x5_sRGB = ::MTL::PixelFormatASTC_10x5_sRGB;
inline constexpr auto PixelFormatASTC_10x6_sRGB = ::MTL::PixelFormatASTC_10x6_sRGB;
inline constexpr auto PixelFormatASTC_10x8_sRGB = ::MTL::PixelFormatASTC_10x8_sRGB;
inline constexpr auto PixelFormatASTC_10x10_sRGB = ::MTL::PixelFormatASTC_10x10_sRGB;
inline constexpr auto PixelFormatASTC_12x10_sRGB = ::MTL::PixelFormatASTC_12x10_sRGB;
inline constexpr auto PixelFormatASTC_12x12_sRGB = ::MTL::PixelFormatASTC_12x12_sRGB;
inline constexpr auto PixelFormatASTC_4x4_LDR = ::MTL::PixelFormatASTC_4x4_LDR;
inline constexpr auto PixelFormatASTC_5x4_LDR = ::MTL::PixelFormatASTC_5x4_LDR;
inline constexpr auto PixelFormatASTC_5x5_LDR = ::MTL::PixelFormatASTC_5x5_LDR;
inline constexpr auto PixelFormatASTC_6x5_LDR = ::MTL::PixelFormatASTC_6x5_LDR;
inline constexpr auto PixelFormatASTC_6x6_LDR = ::MTL::PixelFormatASTC_6x6_LDR;
inline constexpr auto PixelFormatASTC_8x5_LDR = ::MTL::PixelFormatASTC_8x5_LDR;
inline constexpr auto PixelFormatASTC_8x6_LDR = ::MTL::PixelFormatASTC_8x6_LDR;
inline constexpr auto PixelFormatASTC_8x8_LDR = ::MTL::PixelFormatASTC_8x8_LDR;
inline constexpr auto PixelFormatASTC_10x5_LDR = ::MTL::PixelFormatASTC_10x5_LDR;
inline constexpr auto PixelFormatASTC_10x6_LDR = ::MTL::PixelFormatASTC_10x6_LDR;
inline constexpr auto PixelFormatASTC_10x8_LDR = ::MTL::PixelFormatASTC_10x8_LDR;
inline constexpr auto PixelFormatASTC_10x10_LDR = ::MTL::PixelFormatASTC_10x10_LDR;
inline constexpr auto PixelFormatASTC_12x10_LDR = ::MTL::PixelFormatASTC_12x10_LDR;
inline constexpr auto PixelFormatASTC_12x12_LDR = ::MTL::PixelFormatASTC_12x12_LDR;
inline constexpr auto PixelFormatASTC_4x4_HDR = ::MTL::PixelFormatASTC_4x4_HDR;
inline constexpr auto PixelFormatASTC_5x4_HDR = ::MTL::PixelFormatASTC_5x4_HDR;
inline constexpr auto PixelFormatASTC_5x5_HDR = ::MTL::PixelFormatASTC_5x5_HDR;
inline constexpr auto PixelFormatASTC_6x5_HDR = ::MTL::PixelFormatASTC_6x5_HDR;
inline constexpr auto PixelFormatASTC_6x6_HDR = ::MTL::PixelFormatASTC_6x6_HDR;
inline constexpr auto PixelFormatASTC_8x5_HDR = ::MTL::PixelFormatASTC_8x5_HDR;
inline constexpr auto PixelFormatASTC_8x6_HDR = ::MTL::PixelFormatASTC_8x6_HDR;
inline constexpr auto PixelFormatASTC_8x8_HDR = ::MTL::PixelFormatASTC_8x8_HDR;
inline constexpr auto PixelFormatASTC_10x5_HDR = ::MTL::PixelFormatASTC_10x5_HDR;
inline constexpr auto PixelFormatASTC_10x6_HDR = ::MTL::PixelFormatASTC_10x6_HDR;
inline constexpr auto PixelFormatASTC_10x8_HDR = ::MTL::PixelFormatASTC_10x8_HDR;
inline constexpr auto PixelFormatASTC_10x10_HDR = ::MTL::PixelFormatASTC_10x10_HDR;
inline constexpr auto PixelFormatASTC_12x10_HDR = ::MTL::PixelFormatASTC_12x10_HDR;
inline constexpr auto PixelFormatASTC_12x12_HDR = ::MTL::PixelFormatASTC_12x12_HDR;
inline constexpr auto PixelFormatGBGR422 = ::MTL::PixelFormatGBGR422;
inline constexpr auto PixelFormatBGRG422 = ::MTL::PixelFormatBGRG422;
inline constexpr auto PixelFormatDepth16Unorm = ::MTL::PixelFormatDepth16Unorm;
inline constexpr auto PixelFormatDepth32Float = ::MTL::PixelFormatDepth32Float;
inline constexpr auto PixelFormatStencil8 = ::MTL::PixelFormatStencil8;
inline constexpr auto PixelFormatDepth24Unorm_Stencil8 = ::MTL::PixelFormatDepth24Unorm_Stencil8;
inline constexpr auto PixelFormatDepth32Float_Stencil8 = ::MTL::PixelFormatDepth32Float_Stencil8;
inline constexpr auto PixelFormatX32_Stencil8 = ::MTL::PixelFormatX32_Stencil8;
inline constexpr auto PixelFormatX24_Stencil8 = ::MTL::PixelFormatX24_Stencil8;
inline constexpr auto PixelFormatUnspecialized = ::MTL::PixelFormatUnspecialized;
using PrimitiveType = ::MTL::PrimitiveType;
inline constexpr auto PrimitiveTypePoint = ::MTL::PrimitiveTypePoint;
inline constexpr auto PrimitiveTypeLine = ::MTL::PrimitiveTypeLine;
inline constexpr auto PrimitiveTypeLineStrip = ::MTL::PrimitiveTypeLineStrip;
inline constexpr auto PrimitiveTypeTriangle = ::MTL::PrimitiveTypeTriangle;
inline constexpr auto PrimitiveTypeTriangleStrip = ::MTL::PrimitiveTypeTriangleStrip;
using VisibilityResultMode = ::MTL::VisibilityResultMode;
inline constexpr auto VisibilityResultModeDisabled = ::MTL::VisibilityResultModeDisabled;
inline constexpr auto VisibilityResultModeBoolean = ::MTL::VisibilityResultModeBoolean;
inline constexpr auto VisibilityResultModeCounting = ::MTL::VisibilityResultModeCounting;
using CullMode = ::MTL::CullMode;
inline constexpr auto CullModeNone = ::MTL::CullModeNone;
inline constexpr auto CullModeFront = ::MTL::CullModeFront;
inline constexpr auto CullModeBack = ::MTL::CullModeBack;
using Winding = ::MTL::Winding;
inline constexpr auto WindingClockwise = ::MTL::WindingClockwise;
inline constexpr auto WindingCounterClockwise = ::MTL::WindingCounterClockwise;
using DepthClipMode = ::MTL::DepthClipMode;
inline constexpr auto DepthClipModeClip = ::MTL::DepthClipModeClip;
inline constexpr auto DepthClipModeClamp = ::MTL::DepthClipModeClamp;
using TriangleFillMode = ::MTL::TriangleFillMode;
inline constexpr auto TriangleFillModeFill = ::MTL::TriangleFillModeFill;
inline constexpr auto TriangleFillModeLines = ::MTL::TriangleFillModeLines;
using LoadAction = ::MTL::LoadAction;
inline constexpr auto LoadActionDontCare = ::MTL::LoadActionDontCare;
inline constexpr auto LoadActionLoad = ::MTL::LoadActionLoad;
inline constexpr auto LoadActionClear = ::MTL::LoadActionClear;
using StoreAction = ::MTL::StoreAction;
inline constexpr auto StoreActionDontCare = ::MTL::StoreActionDontCare;
inline constexpr auto StoreActionStore = ::MTL::StoreActionStore;
inline constexpr auto StoreActionMultisampleResolve = ::MTL::StoreActionMultisampleResolve;
inline constexpr auto StoreActionStoreAndMultisampleResolve =
    ::MTL::StoreActionStoreAndMultisampleResolve;
inline constexpr auto StoreActionUnknown = ::MTL::StoreActionUnknown;
inline constexpr auto StoreActionCustomSampleDepthStore = ::MTL::StoreActionCustomSampleDepthStore;
using VisibilityResultType = ::MTL::VisibilityResultType;
inline constexpr auto VisibilityResultTypeReset = ::MTL::VisibilityResultTypeReset;
inline constexpr auto VisibilityResultTypeAccumulate = ::MTL::VisibilityResultTypeAccumulate;
using MultisampleDepthResolveFilter = ::MTL::MultisampleDepthResolveFilter;
inline constexpr auto MultisampleDepthResolveFilterSample0 =
    ::MTL::MultisampleDepthResolveFilterSample0;
inline constexpr auto MultisampleDepthResolveFilterMin = ::MTL::MultisampleDepthResolveFilterMin;
inline constexpr auto MultisampleDepthResolveFilterMax = ::MTL::MultisampleDepthResolveFilterMax;
using MultisampleStencilResolveFilter = ::MTL::MultisampleStencilResolveFilter;
inline constexpr auto MultisampleStencilResolveFilterSample0 =
    ::MTL::MultisampleStencilResolveFilterSample0;
inline constexpr auto MultisampleStencilResolveFilterDepthResolvedSample =
    ::MTL::MultisampleStencilResolveFilterDepthResolvedSample;
using BlendFactor = ::MTL::BlendFactor;
inline constexpr auto BlendFactorZero = ::MTL::BlendFactorZero;
inline constexpr auto BlendFactorOne = ::MTL::BlendFactorOne;
inline constexpr auto BlendFactorSourceColor = ::MTL::BlendFactorSourceColor;
inline constexpr auto BlendFactorOneMinusSourceColor = ::MTL::BlendFactorOneMinusSourceColor;
inline constexpr auto BlendFactorSourceAlpha = ::MTL::BlendFactorSourceAlpha;
inline constexpr auto BlendFactorOneMinusSourceAlpha = ::MTL::BlendFactorOneMinusSourceAlpha;
inline constexpr auto BlendFactorDestinationColor = ::MTL::BlendFactorDestinationColor;
inline constexpr auto BlendFactorOneMinusDestinationColor =
    ::MTL::BlendFactorOneMinusDestinationColor;
inline constexpr auto BlendFactorDestinationAlpha = ::MTL::BlendFactorDestinationAlpha;
inline constexpr auto BlendFactorOneMinusDestinationAlpha =
    ::MTL::BlendFactorOneMinusDestinationAlpha;
inline constexpr auto BlendFactorSourceAlphaSaturated = ::MTL::BlendFactorSourceAlphaSaturated;
inline constexpr auto BlendFactorBlendColor = ::MTL::BlendFactorBlendColor;
inline constexpr auto BlendFactorOneMinusBlendColor = ::MTL::BlendFactorOneMinusBlendColor;
inline constexpr auto BlendFactorBlendAlpha = ::MTL::BlendFactorBlendAlpha;
inline constexpr auto BlendFactorOneMinusBlendAlpha = ::MTL::BlendFactorOneMinusBlendAlpha;
inline constexpr auto BlendFactorSource1Color = ::MTL::BlendFactorSource1Color;
inline constexpr auto BlendFactorOneMinusSource1Color = ::MTL::BlendFactorOneMinusSource1Color;
inline constexpr auto BlendFactorSource1Alpha = ::MTL::BlendFactorSource1Alpha;
inline constexpr auto BlendFactorOneMinusSource1Alpha = ::MTL::BlendFactorOneMinusSource1Alpha;
inline constexpr auto BlendFactorUnspecialized = ::MTL::BlendFactorUnspecialized;
using BlendOperation = ::MTL::BlendOperation;
inline constexpr auto BlendOperationAdd = ::MTL::BlendOperationAdd;
inline constexpr auto BlendOperationSubtract = ::MTL::BlendOperationSubtract;
inline constexpr auto BlendOperationReverseSubtract = ::MTL::BlendOperationReverseSubtract;
inline constexpr auto BlendOperationMin = ::MTL::BlendOperationMin;
inline constexpr auto BlendOperationMax = ::MTL::BlendOperationMax;
inline constexpr auto BlendOperationUnspecialized = ::MTL::BlendOperationUnspecialized;
using PrimitiveTopologyClass = ::MTL::PrimitiveTopologyClass;
inline constexpr auto PrimitiveTopologyClassUnspecified = ::MTL::PrimitiveTopologyClassUnspecified;
inline constexpr auto PrimitiveTopologyClassPoint = ::MTL::PrimitiveTopologyClassPoint;
inline constexpr auto PrimitiveTopologyClassLine = ::MTL::PrimitiveTopologyClassLine;
inline constexpr auto PrimitiveTopologyClassTriangle = ::MTL::PrimitiveTopologyClassTriangle;
using TessellationPartitionMode = ::MTL::TessellationPartitionMode;
inline constexpr auto TessellationPartitionModePow2 = ::MTL::TessellationPartitionModePow2;
inline constexpr auto TessellationPartitionModeInteger = ::MTL::TessellationPartitionModeInteger;
inline constexpr auto TessellationPartitionModeFractionalOdd =
    ::MTL::TessellationPartitionModeFractionalOdd;
inline constexpr auto TessellationPartitionModeFractionalEven =
    ::MTL::TessellationPartitionModeFractionalEven;
using TessellationFactorStepFunction = ::MTL::TessellationFactorStepFunction;
inline constexpr auto TessellationFactorStepFunctionConstant =
    ::MTL::TessellationFactorStepFunctionConstant;
inline constexpr auto TessellationFactorStepFunctionPerPatch =
    ::MTL::TessellationFactorStepFunctionPerPatch;
inline constexpr auto TessellationFactorStepFunctionPerInstance =
    ::MTL::TessellationFactorStepFunctionPerInstance;
inline constexpr auto TessellationFactorStepFunctionPerPatchAndPerInstance =
    ::MTL::TessellationFactorStepFunctionPerPatchAndPerInstance;
using TessellationFactorFormat = ::MTL::TessellationFactorFormat;
inline constexpr auto TessellationFactorFormatHalf = ::MTL::TessellationFactorFormatHalf;
using TessellationControlPointIndexType = ::MTL::TessellationControlPointIndexType;
inline constexpr auto TessellationControlPointIndexTypeNone =
    ::MTL::TessellationControlPointIndexTypeNone;
inline constexpr auto TessellationControlPointIndexTypeUInt16 =
    ::MTL::TessellationControlPointIndexTypeUInt16;
inline constexpr auto TessellationControlPointIndexTypeUInt32 =
    ::MTL::TessellationControlPointIndexTypeUInt32;
using PurgeableState = ::MTL::PurgeableState;
inline constexpr auto PurgeableStateKeepCurrent = ::MTL::PurgeableStateKeepCurrent;
inline constexpr auto PurgeableStateNonVolatile = ::MTL::PurgeableStateNonVolatile;
inline constexpr auto PurgeableStateVolatile = ::MTL::PurgeableStateVolatile;
inline constexpr auto PurgeableStateEmpty = ::MTL::PurgeableStateEmpty;
using CPUCacheMode = ::MTL::CPUCacheMode;
inline constexpr auto CPUCacheModeDefaultCache = ::MTL::CPUCacheModeDefaultCache;
inline constexpr auto CPUCacheModeWriteCombined = ::MTL::CPUCacheModeWriteCombined;
using StorageMode = ::MTL::StorageMode;
inline constexpr auto StorageModeShared = ::MTL::StorageModeShared;
inline constexpr auto StorageModeManaged = ::MTL::StorageModeManaged;
inline constexpr auto StorageModePrivate = ::MTL::StorageModePrivate;
inline constexpr auto StorageModeMemoryless = ::MTL::StorageModeMemoryless;
using HazardTrackingMode = ::MTL::HazardTrackingMode;
inline constexpr auto HazardTrackingModeDefault = ::MTL::HazardTrackingModeDefault;
inline constexpr auto HazardTrackingModeUntracked = ::MTL::HazardTrackingModeUntracked;
inline constexpr auto HazardTrackingModeTracked = ::MTL::HazardTrackingModeTracked;
using SparsePageSize = ::MTL::SparsePageSize;
inline constexpr auto SparsePageSize16 = ::MTL::SparsePageSize16;
inline constexpr auto SparsePageSize64 = ::MTL::SparsePageSize64;
inline constexpr auto SparsePageSize256 = ::MTL::SparsePageSize256;
using BufferSparseTier = ::MTL::BufferSparseTier;
inline constexpr auto BufferSparseTierNone = ::MTL::BufferSparseTierNone;
inline constexpr auto BufferSparseTier1 = ::MTL::BufferSparseTier1;
using TextureSparseTier = ::MTL::TextureSparseTier;
inline constexpr auto TextureSparseTierNone = ::MTL::TextureSparseTierNone;
inline constexpr auto TextureSparseTier1 = ::MTL::TextureSparseTier1;
inline constexpr auto TextureSparseTier2 = ::MTL::TextureSparseTier2;
using SparseTextureMappingMode = ::MTL::SparseTextureMappingMode;
inline constexpr auto SparseTextureMappingModeMap = ::MTL::SparseTextureMappingModeMap;
inline constexpr auto SparseTextureMappingModeUnmap = ::MTL::SparseTextureMappingModeUnmap;
using SamplerMinMagFilter = ::MTL::SamplerMinMagFilter;
inline constexpr auto SamplerMinMagFilterNearest = ::MTL::SamplerMinMagFilterNearest;
inline constexpr auto SamplerMinMagFilterLinear = ::MTL::SamplerMinMagFilterLinear;
using SamplerMipFilter = ::MTL::SamplerMipFilter;
inline constexpr auto SamplerMipFilterNotMipmapped = ::MTL::SamplerMipFilterNotMipmapped;
inline constexpr auto SamplerMipFilterNearest = ::MTL::SamplerMipFilterNearest;
inline constexpr auto SamplerMipFilterLinear = ::MTL::SamplerMipFilterLinear;
using SamplerAddressMode = ::MTL::SamplerAddressMode;
inline constexpr auto SamplerAddressModeClampToEdge = ::MTL::SamplerAddressModeClampToEdge;
inline constexpr auto SamplerAddressModeMirrorClampToEdge =
    ::MTL::SamplerAddressModeMirrorClampToEdge;
inline constexpr auto SamplerAddressModeRepeat = ::MTL::SamplerAddressModeRepeat;
inline constexpr auto SamplerAddressModeMirrorRepeat = ::MTL::SamplerAddressModeMirrorRepeat;
inline constexpr auto SamplerAddressModeClampToZero = ::MTL::SamplerAddressModeClampToZero;
inline constexpr auto SamplerAddressModeClampToBorderColor =
    ::MTL::SamplerAddressModeClampToBorderColor;
using SamplerBorderColor = ::MTL::SamplerBorderColor;
inline constexpr auto SamplerBorderColorTransparentBlack =
    ::MTL::SamplerBorderColorTransparentBlack;
inline constexpr auto SamplerBorderColorOpaqueBlack = ::MTL::SamplerBorderColorOpaqueBlack;
inline constexpr auto SamplerBorderColorOpaqueWhite = ::MTL::SamplerBorderColorOpaqueWhite;
using SamplerReductionMode = ::MTL::SamplerReductionMode;
inline constexpr auto SamplerReductionModeWeightedAverage =
    ::MTL::SamplerReductionModeWeightedAverage;
inline constexpr auto SamplerReductionModeMinimum = ::MTL::SamplerReductionModeMinimum;
inline constexpr auto SamplerReductionModeMaximum = ::MTL::SamplerReductionModeMaximum;
using AttributeFormat = ::MTL::AttributeFormat;
inline constexpr auto AttributeFormatInvalid = ::MTL::AttributeFormatInvalid;
inline constexpr auto AttributeFormatUChar2 = ::MTL::AttributeFormatUChar2;
inline constexpr auto AttributeFormatUChar3 = ::MTL::AttributeFormatUChar3;
inline constexpr auto AttributeFormatUChar4 = ::MTL::AttributeFormatUChar4;
inline constexpr auto AttributeFormatChar2 = ::MTL::AttributeFormatChar2;
inline constexpr auto AttributeFormatChar3 = ::MTL::AttributeFormatChar3;
inline constexpr auto AttributeFormatChar4 = ::MTL::AttributeFormatChar4;
inline constexpr auto AttributeFormatUChar2Normalized = ::MTL::AttributeFormatUChar2Normalized;
inline constexpr auto AttributeFormatUChar3Normalized = ::MTL::AttributeFormatUChar3Normalized;
inline constexpr auto AttributeFormatUChar4Normalized = ::MTL::AttributeFormatUChar4Normalized;
inline constexpr auto AttributeFormatChar2Normalized = ::MTL::AttributeFormatChar2Normalized;
inline constexpr auto AttributeFormatChar3Normalized = ::MTL::AttributeFormatChar3Normalized;
inline constexpr auto AttributeFormatChar4Normalized = ::MTL::AttributeFormatChar4Normalized;
inline constexpr auto AttributeFormatUShort2 = ::MTL::AttributeFormatUShort2;
inline constexpr auto AttributeFormatUShort3 = ::MTL::AttributeFormatUShort3;
inline constexpr auto AttributeFormatUShort4 = ::MTL::AttributeFormatUShort4;
inline constexpr auto AttributeFormatShort2 = ::MTL::AttributeFormatShort2;
inline constexpr auto AttributeFormatShort3 = ::MTL::AttributeFormatShort3;
inline constexpr auto AttributeFormatShort4 = ::MTL::AttributeFormatShort4;
inline constexpr auto AttributeFormatUShort2Normalized = ::MTL::AttributeFormatUShort2Normalized;
inline constexpr auto AttributeFormatUShort3Normalized = ::MTL::AttributeFormatUShort3Normalized;
inline constexpr auto AttributeFormatUShort4Normalized = ::MTL::AttributeFormatUShort4Normalized;
inline constexpr auto AttributeFormatShort2Normalized = ::MTL::AttributeFormatShort2Normalized;
inline constexpr auto AttributeFormatShort3Normalized = ::MTL::AttributeFormatShort3Normalized;
inline constexpr auto AttributeFormatShort4Normalized = ::MTL::AttributeFormatShort4Normalized;
inline constexpr auto AttributeFormatHalf2 = ::MTL::AttributeFormatHalf2;
inline constexpr auto AttributeFormatHalf3 = ::MTL::AttributeFormatHalf3;
inline constexpr auto AttributeFormatHalf4 = ::MTL::AttributeFormatHalf4;
inline constexpr auto AttributeFormatFloat = ::MTL::AttributeFormatFloat;
inline constexpr auto AttributeFormatFloat2 = ::MTL::AttributeFormatFloat2;
inline constexpr auto AttributeFormatFloat3 = ::MTL::AttributeFormatFloat3;
inline constexpr auto AttributeFormatFloat4 = ::MTL::AttributeFormatFloat4;
inline constexpr auto AttributeFormatInt = ::MTL::AttributeFormatInt;
inline constexpr auto AttributeFormatInt2 = ::MTL::AttributeFormatInt2;
inline constexpr auto AttributeFormatInt3 = ::MTL::AttributeFormatInt3;
inline constexpr auto AttributeFormatInt4 = ::MTL::AttributeFormatInt4;
inline constexpr auto AttributeFormatUInt = ::MTL::AttributeFormatUInt;
inline constexpr auto AttributeFormatUInt2 = ::MTL::AttributeFormatUInt2;
inline constexpr auto AttributeFormatUInt3 = ::MTL::AttributeFormatUInt3;
inline constexpr auto AttributeFormatUInt4 = ::MTL::AttributeFormatUInt4;
inline constexpr auto AttributeFormatInt1010102Normalized =
    ::MTL::AttributeFormatInt1010102Normalized;
inline constexpr auto AttributeFormatUInt1010102Normalized =
    ::MTL::AttributeFormatUInt1010102Normalized;
inline constexpr auto AttributeFormatUChar4Normalized_BGRA =
    ::MTL::AttributeFormatUChar4Normalized_BGRA;
inline constexpr auto AttributeFormatUChar = ::MTL::AttributeFormatUChar;
inline constexpr auto AttributeFormatChar = ::MTL::AttributeFormatChar;
inline constexpr auto AttributeFormatUCharNormalized = ::MTL::AttributeFormatUCharNormalized;
inline constexpr auto AttributeFormatCharNormalized = ::MTL::AttributeFormatCharNormalized;
inline constexpr auto AttributeFormatUShort = ::MTL::AttributeFormatUShort;
inline constexpr auto AttributeFormatShort = ::MTL::AttributeFormatShort;
inline constexpr auto AttributeFormatUShortNormalized = ::MTL::AttributeFormatUShortNormalized;
inline constexpr auto AttributeFormatShortNormalized = ::MTL::AttributeFormatShortNormalized;
inline constexpr auto AttributeFormatHalf = ::MTL::AttributeFormatHalf;
inline constexpr auto AttributeFormatFloatRG11B10 = ::MTL::AttributeFormatFloatRG11B10;
inline constexpr auto AttributeFormatFloatRGB9E5 = ::MTL::AttributeFormatFloatRGB9E5;
using StepFunction = ::MTL::StepFunction;
inline constexpr auto StepFunctionConstant = ::MTL::StepFunctionConstant;
inline constexpr auto StepFunctionPerVertex = ::MTL::StepFunctionPerVertex;
inline constexpr auto StepFunctionPerInstance = ::MTL::StepFunctionPerInstance;
inline constexpr auto StepFunctionPerPatch = ::MTL::StepFunctionPerPatch;
inline constexpr auto StepFunctionPerPatchControlPoint = ::MTL::StepFunctionPerPatchControlPoint;
inline constexpr auto StepFunctionThreadPositionInGridX = ::MTL::StepFunctionThreadPositionInGridX;
inline constexpr auto StepFunctionThreadPositionInGridY = ::MTL::StepFunctionThreadPositionInGridY;
inline constexpr auto StepFunctionThreadPositionInGridXIndexed =
    ::MTL::StepFunctionThreadPositionInGridXIndexed;
inline constexpr auto StepFunctionThreadPositionInGridYIndexed =
    ::MTL::StepFunctionThreadPositionInGridYIndexed;
using TensorDataType = ::MTL::TensorDataType;
inline constexpr auto TensorDataTypeNone = ::MTL::TensorDataTypeNone;
inline constexpr auto TensorDataTypeFloat32 = ::MTL::TensorDataTypeFloat32;
inline constexpr auto TensorDataTypeFloat16 = ::MTL::TensorDataTypeFloat16;
inline constexpr auto TensorDataTypeBFloat16 = ::MTL::TensorDataTypeBFloat16;
inline constexpr auto TensorDataTypeInt8 = ::MTL::TensorDataTypeInt8;
inline constexpr auto TensorDataTypeUInt8 = ::MTL::TensorDataTypeUInt8;
inline constexpr auto TensorDataTypeInt16 = ::MTL::TensorDataTypeInt16;
inline constexpr auto TensorDataTypeUInt16 = ::MTL::TensorDataTypeUInt16;
inline constexpr auto TensorDataTypeInt32 = ::MTL::TensorDataTypeInt32;
inline constexpr auto TensorDataTypeUInt32 = ::MTL::TensorDataTypeUInt32;
inline constexpr auto TensorDataTypeInt4 = ::MTL::TensorDataTypeInt4;
inline constexpr auto TensorDataTypeUInt4 = ::MTL::TensorDataTypeUInt4;
inline constexpr auto TensorDataTypeMetalFloat8UE8M0 = ::MTL::TensorDataTypeMetalFloat8UE8M0;
inline constexpr auto TensorDataTypeUInt2 = ::MTL::TensorDataTypeUInt2;
inline constexpr auto TensorDataTypeInt2 = ::MTL::TensorDataTypeInt2;
inline constexpr auto TensorDataTypeMetalFloat8E5M2 = ::MTL::TensorDataTypeMetalFloat8E5M2;
inline constexpr auto TensorDataTypeMetalFloat8E4M3 = ::MTL::TensorDataTypeMetalFloat8E4M3;
inline constexpr auto TensorDataTypeMetalFloat4E2M1 = ::MTL::TensorDataTypeMetalFloat4E2M1;
using TensorError = ::MTL::TensorError;
inline constexpr auto TensorErrorNone = ::MTL::TensorErrorNone;
inline constexpr auto TensorErrorInternalError = ::MTL::TensorErrorInternalError;
inline constexpr auto TensorErrorInvalidDescriptor = ::MTL::TensorErrorInvalidDescriptor;
using TensorPlaneType = ::MTL::TensorPlaneType;
inline constexpr auto TensorPlaneTypeData = ::MTL::TensorPlaneTypeData;
inline constexpr auto TensorPlaneTypeScales = ::MTL::TensorPlaneTypeScales;
using TextureType = ::MTL::TextureType;
inline constexpr auto TextureType1D = ::MTL::TextureType1D;
inline constexpr auto TextureType1DArray = ::MTL::TextureType1DArray;
inline constexpr auto TextureType2D = ::MTL::TextureType2D;
inline constexpr auto TextureType2DArray = ::MTL::TextureType2DArray;
inline constexpr auto TextureType2DMultisample = ::MTL::TextureType2DMultisample;
inline constexpr auto TextureTypeCube = ::MTL::TextureTypeCube;
inline constexpr auto TextureTypeCubeArray = ::MTL::TextureTypeCubeArray;
inline constexpr auto TextureType3D = ::MTL::TextureType3D;
inline constexpr auto TextureType2DMultisampleArray = ::MTL::TextureType2DMultisampleArray;
inline constexpr auto TextureTypeTextureBuffer = ::MTL::TextureTypeTextureBuffer;
using TextureSwizzle = ::MTL::TextureSwizzle;
inline constexpr auto TextureSwizzleZero = ::MTL::TextureSwizzleZero;
inline constexpr auto TextureSwizzleOne = ::MTL::TextureSwizzleOne;
inline constexpr auto TextureSwizzleRed = ::MTL::TextureSwizzleRed;
inline constexpr auto TextureSwizzleGreen = ::MTL::TextureSwizzleGreen;
inline constexpr auto TextureSwizzleBlue = ::MTL::TextureSwizzleBlue;
inline constexpr auto TextureSwizzleAlpha = ::MTL::TextureSwizzleAlpha;
using TextureCompressionType = ::MTL::TextureCompressionType;
inline constexpr auto TextureCompressionTypeLossless = ::MTL::TextureCompressionTypeLossless;
inline constexpr auto TextureCompressionTypeLossy = ::MTL::TextureCompressionTypeLossy;
using VertexFormat = ::MTL::VertexFormat;
inline constexpr auto VertexFormatInvalid = ::MTL::VertexFormatInvalid;
inline constexpr auto VertexFormatUChar2 = ::MTL::VertexFormatUChar2;
inline constexpr auto VertexFormatUChar3 = ::MTL::VertexFormatUChar3;
inline constexpr auto VertexFormatUChar4 = ::MTL::VertexFormatUChar4;
inline constexpr auto VertexFormatChar2 = ::MTL::VertexFormatChar2;
inline constexpr auto VertexFormatChar3 = ::MTL::VertexFormatChar3;
inline constexpr auto VertexFormatChar4 = ::MTL::VertexFormatChar4;
inline constexpr auto VertexFormatUChar2Normalized = ::MTL::VertexFormatUChar2Normalized;
inline constexpr auto VertexFormatUChar3Normalized = ::MTL::VertexFormatUChar3Normalized;
inline constexpr auto VertexFormatUChar4Normalized = ::MTL::VertexFormatUChar4Normalized;
inline constexpr auto VertexFormatChar2Normalized = ::MTL::VertexFormatChar2Normalized;
inline constexpr auto VertexFormatChar3Normalized = ::MTL::VertexFormatChar3Normalized;
inline constexpr auto VertexFormatChar4Normalized = ::MTL::VertexFormatChar4Normalized;
inline constexpr auto VertexFormatUShort2 = ::MTL::VertexFormatUShort2;
inline constexpr auto VertexFormatUShort3 = ::MTL::VertexFormatUShort3;
inline constexpr auto VertexFormatUShort4 = ::MTL::VertexFormatUShort4;
inline constexpr auto VertexFormatShort2 = ::MTL::VertexFormatShort2;
inline constexpr auto VertexFormatShort3 = ::MTL::VertexFormatShort3;
inline constexpr auto VertexFormatShort4 = ::MTL::VertexFormatShort4;
inline constexpr auto VertexFormatUShort2Normalized = ::MTL::VertexFormatUShort2Normalized;
inline constexpr auto VertexFormatUShort3Normalized = ::MTL::VertexFormatUShort3Normalized;
inline constexpr auto VertexFormatUShort4Normalized = ::MTL::VertexFormatUShort4Normalized;
inline constexpr auto VertexFormatShort2Normalized = ::MTL::VertexFormatShort2Normalized;
inline constexpr auto VertexFormatShort3Normalized = ::MTL::VertexFormatShort3Normalized;
inline constexpr auto VertexFormatShort4Normalized = ::MTL::VertexFormatShort4Normalized;
inline constexpr auto VertexFormatHalf2 = ::MTL::VertexFormatHalf2;
inline constexpr auto VertexFormatHalf3 = ::MTL::VertexFormatHalf3;
inline constexpr auto VertexFormatHalf4 = ::MTL::VertexFormatHalf4;
inline constexpr auto VertexFormatFloat = ::MTL::VertexFormatFloat;
inline constexpr auto VertexFormatFloat2 = ::MTL::VertexFormatFloat2;
inline constexpr auto VertexFormatFloat3 = ::MTL::VertexFormatFloat3;
inline constexpr auto VertexFormatFloat4 = ::MTL::VertexFormatFloat4;
inline constexpr auto VertexFormatInt = ::MTL::VertexFormatInt;
inline constexpr auto VertexFormatInt2 = ::MTL::VertexFormatInt2;
inline constexpr auto VertexFormatInt3 = ::MTL::VertexFormatInt3;
inline constexpr auto VertexFormatInt4 = ::MTL::VertexFormatInt4;
inline constexpr auto VertexFormatUInt = ::MTL::VertexFormatUInt;
inline constexpr auto VertexFormatUInt2 = ::MTL::VertexFormatUInt2;
inline constexpr auto VertexFormatUInt3 = ::MTL::VertexFormatUInt3;
inline constexpr auto VertexFormatUInt4 = ::MTL::VertexFormatUInt4;
inline constexpr auto VertexFormatInt1010102Normalized = ::MTL::VertexFormatInt1010102Normalized;
inline constexpr auto VertexFormatUInt1010102Normalized = ::MTL::VertexFormatUInt1010102Normalized;
inline constexpr auto VertexFormatUChar4Normalized_BGRA = ::MTL::VertexFormatUChar4Normalized_BGRA;
inline constexpr auto VertexFormatUChar = ::MTL::VertexFormatUChar;
inline constexpr auto VertexFormatChar = ::MTL::VertexFormatChar;
inline constexpr auto VertexFormatUCharNormalized = ::MTL::VertexFormatUCharNormalized;
inline constexpr auto VertexFormatCharNormalized = ::MTL::VertexFormatCharNormalized;
inline constexpr auto VertexFormatUShort = ::MTL::VertexFormatUShort;
inline constexpr auto VertexFormatShort = ::MTL::VertexFormatShort;
inline constexpr auto VertexFormatUShortNormalized = ::MTL::VertexFormatUShortNormalized;
inline constexpr auto VertexFormatShortNormalized = ::MTL::VertexFormatShortNormalized;
inline constexpr auto VertexFormatHalf = ::MTL::VertexFormatHalf;
inline constexpr auto VertexFormatFloatRG11B10 = ::MTL::VertexFormatFloatRG11B10;
inline constexpr auto VertexFormatFloatRGB9E5 = ::MTL::VertexFormatFloatRGB9E5;
using VertexStepFunction = ::MTL::VertexStepFunction;
inline constexpr auto VertexStepFunctionConstant = ::MTL::VertexStepFunctionConstant;
inline constexpr auto VertexStepFunctionPerVertex = ::MTL::VertexStepFunctionPerVertex;
inline constexpr auto VertexStepFunctionPerInstance = ::MTL::VertexStepFunctionPerInstance;
inline constexpr auto VertexStepFunctionPerPatch = ::MTL::VertexStepFunctionPerPatch;
inline constexpr auto VertexStepFunctionPerPatchControlPoint =
    ::MTL::VertexStepFunctionPerPatchControlPoint;
using AccelerationStructureRefitOptions = ::MTL::AccelerationStructureRefitOptions;
inline constexpr auto AccelerationStructureRefitOptionVertexData =
    ::MTL::AccelerationStructureRefitOptionVertexData;
inline constexpr auto AccelerationStructureRefitOptionPerPrimitiveData =
    ::MTL::AccelerationStructureRefitOptionPerPrimitiveData;
using AccelerationStructureUsage = ::MTL::AccelerationStructureUsage;
inline constexpr auto AccelerationStructureUsageNone = ::MTL::AccelerationStructureUsageNone;
inline constexpr auto AccelerationStructureUsageRefit = ::MTL::AccelerationStructureUsageRefit;
inline constexpr auto AccelerationStructureUsagePreferFastBuild =
    ::MTL::AccelerationStructureUsagePreferFastBuild;
inline constexpr auto AccelerationStructureUsageExtendedLimits =
    ::MTL::AccelerationStructureUsageExtendedLimits;
inline constexpr auto AccelerationStructureUsagePreferFastIntersection =
    ::MTL::AccelerationStructureUsagePreferFastIntersection;
inline constexpr auto AccelerationStructureUsageMinimizeMemory =
    ::MTL::AccelerationStructureUsageMinimizeMemory;
using AccelerationStructureInstanceOptions = ::MTL::AccelerationStructureInstanceOptions;
inline constexpr auto AccelerationStructureInstanceOptionNone =
    ::MTL::AccelerationStructureInstanceOptionNone;
inline constexpr auto AccelerationStructureInstanceOptionDisableTriangleCulling =
    ::MTL::AccelerationStructureInstanceOptionDisableTriangleCulling;
inline constexpr auto
    AccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise =
        ::MTL::AccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise;
inline constexpr auto AccelerationStructureInstanceOptionOpaque =
    ::MTL::AccelerationStructureInstanceOptionOpaque;
inline constexpr auto AccelerationStructureInstanceOptionNonOpaque =
    ::MTL::AccelerationStructureInstanceOptionNonOpaque;
using BlitOption = ::MTL::BlitOption;
inline constexpr auto BlitOptionNone = ::MTL::BlitOptionNone;
inline constexpr auto BlitOptionDepthFromDepthStencil = ::MTL::BlitOptionDepthFromDepthStencil;
inline constexpr auto BlitOptionStencilFromDepthStencil = ::MTL::BlitOptionStencilFromDepthStencil;
inline constexpr auto BlitOptionRowLinearPVRTC = ::MTL::BlitOptionRowLinearPVRTC;
using CommandBufferErrorOption = ::MTL::CommandBufferErrorOption;
inline constexpr auto CommandBufferErrorOptionNone = ::MTL::CommandBufferErrorOptionNone;
inline constexpr auto CommandBufferErrorOptionEncoderExecutionStatus =
    ::MTL::CommandBufferErrorOptionEncoderExecutionStatus;
using ResourceUsage = ::MTL::ResourceUsage;
inline constexpr auto ResourceUsageRead = ::MTL::ResourceUsageRead;
inline constexpr auto ResourceUsageWrite = ::MTL::ResourceUsageWrite;
inline constexpr auto ResourceUsageSample = ::MTL::ResourceUsageSample;
using BarrierScope = ::MTL::BarrierScope;
inline constexpr auto BarrierScopeBuffers = ::MTL::BarrierScopeBuffers;
inline constexpr auto BarrierScopeTextures = ::MTL::BarrierScopeTextures;
inline constexpr auto BarrierScopeRenderTargets = ::MTL::BarrierScopeRenderTargets;
using Stages = ::MTL::Stages;
inline constexpr auto StageVertex = ::MTL::StageVertex;
inline constexpr auto StageFragment = ::MTL::StageFragment;
inline constexpr auto StageTile = ::MTL::StageTile;
inline constexpr auto StageObject = ::MTL::StageObject;
inline constexpr auto StageMesh = ::MTL::StageMesh;
inline constexpr auto StageResourceState = ::MTL::StageResourceState;
inline constexpr auto StageDispatch = ::MTL::StageDispatch;
inline constexpr auto StageBlit = ::MTL::StageBlit;
inline constexpr auto StageAccelerationStructure = ::MTL::StageAccelerationStructure;
inline constexpr auto StageMachineLearning = ::MTL::StageMachineLearning;
inline constexpr auto StageAll = ::MTL::StageAll;
using PipelineOption = ::MTL::PipelineOption;
inline constexpr auto PipelineOptionNone = ::MTL::PipelineOptionNone;
inline constexpr auto PipelineOptionArgumentInfo = ::MTL::PipelineOptionArgumentInfo;
inline constexpr auto PipelineOptionBindingInfo = ::MTL::PipelineOptionBindingInfo;
inline constexpr auto PipelineOptionBufferTypeInfo = ::MTL::PipelineOptionBufferTypeInfo;
inline constexpr auto PipelineOptionFailOnBinaryArchiveMiss =
    ::MTL::PipelineOptionFailOnBinaryArchiveMiss;
using FunctionOptions = ::MTL::FunctionOptions;
inline constexpr auto FunctionOptionNone = ::MTL::FunctionOptionNone;
inline constexpr auto FunctionOptionCompileToBinary = ::MTL::FunctionOptionCompileToBinary;
inline constexpr auto FunctionOptionStoreFunctionInMetalPipelinesScript =
    ::MTL::FunctionOptionStoreFunctionInMetalPipelinesScript;
inline constexpr auto FunctionOptionStoreFunctionInMetalScript =
    ::MTL::FunctionOptionStoreFunctionInMetalScript;
inline constexpr auto FunctionOptionFailOnBinaryArchiveMiss =
    ::MTL::FunctionOptionFailOnBinaryArchiveMiss;
inline constexpr auto FunctionOptionPipelineIndependent = ::MTL::FunctionOptionPipelineIndependent;
using StitchedLibraryOptions = ::MTL::StitchedLibraryOptions;
inline constexpr auto StitchedLibraryOptionNone = ::MTL::StitchedLibraryOptionNone;
inline constexpr auto StitchedLibraryOptionFailOnBinaryArchiveMiss =
    ::MTL::StitchedLibraryOptionFailOnBinaryArchiveMiss;
inline constexpr auto StitchedLibraryOptionStoreLibraryInMetalPipelinesScript =
    ::MTL::StitchedLibraryOptionStoreLibraryInMetalPipelinesScript;
using IndirectCommandType = ::MTL::IndirectCommandType;
inline constexpr auto IndirectCommandTypeDraw = ::MTL::IndirectCommandTypeDraw;
inline constexpr auto IndirectCommandTypeDrawIndexed = ::MTL::IndirectCommandTypeDrawIndexed;
inline constexpr auto IndirectCommandTypeDrawPatches = ::MTL::IndirectCommandTypeDrawPatches;
inline constexpr auto IndirectCommandTypeDrawIndexedPatches =
    ::MTL::IndirectCommandTypeDrawIndexedPatches;
inline constexpr auto IndirectCommandTypeConcurrentDispatch =
    ::MTL::IndirectCommandTypeConcurrentDispatch;
inline constexpr auto IndirectCommandTypeConcurrentDispatchThreads =
    ::MTL::IndirectCommandTypeConcurrentDispatchThreads;
inline constexpr auto IndirectCommandTypeDrawMeshThreadgroups =
    ::MTL::IndirectCommandTypeDrawMeshThreadgroups;
inline constexpr auto IndirectCommandTypeDrawMeshThreads =
    ::MTL::IndirectCommandTypeDrawMeshThreads;
using IntersectionFunctionSignature = ::MTL::IntersectionFunctionSignature;
inline constexpr auto IntersectionFunctionSignatureNone = ::MTL::IntersectionFunctionSignatureNone;
inline constexpr auto IntersectionFunctionSignatureInstancing =
    ::MTL::IntersectionFunctionSignatureInstancing;
inline constexpr auto IntersectionFunctionSignatureTriangleData =
    ::MTL::IntersectionFunctionSignatureTriangleData;
inline constexpr auto IntersectionFunctionSignatureWorldSpaceData =
    ::MTL::IntersectionFunctionSignatureWorldSpaceData;
inline constexpr auto IntersectionFunctionSignatureInstanceMotion =
    ::MTL::IntersectionFunctionSignatureInstanceMotion;
inline constexpr auto IntersectionFunctionSignaturePrimitiveMotion =
    ::MTL::IntersectionFunctionSignaturePrimitiveMotion;
inline constexpr auto IntersectionFunctionSignatureExtendedLimits =
    ::MTL::IntersectionFunctionSignatureExtendedLimits;
inline constexpr auto IntersectionFunctionSignatureMaxLevels =
    ::MTL::IntersectionFunctionSignatureMaxLevels;
inline constexpr auto IntersectionFunctionSignatureCurveData =
    ::MTL::IntersectionFunctionSignatureCurveData;
inline constexpr auto IntersectionFunctionSignatureIntersectionFunctionBuffer =
    ::MTL::IntersectionFunctionSignatureIntersectionFunctionBuffer;
inline constexpr auto IntersectionFunctionSignatureUserData =
    ::MTL::IntersectionFunctionSignatureUserData;
using RenderStages = ::MTL::RenderStages;
inline constexpr auto RenderStageVertex = ::MTL::RenderStageVertex;
inline constexpr auto RenderStageFragment = ::MTL::RenderStageFragment;
inline constexpr auto RenderStageTile = ::MTL::RenderStageTile;
inline constexpr auto RenderStageObject = ::MTL::RenderStageObject;
inline constexpr auto RenderStageMesh = ::MTL::RenderStageMesh;
using StoreActionOptions = ::MTL::StoreActionOptions;
inline constexpr auto StoreActionOptionNone = ::MTL::StoreActionOptionNone;
inline constexpr auto StoreActionOptionCustomSamplePositions =
    ::MTL::StoreActionOptionCustomSamplePositions;
inline constexpr auto StoreActionOptionValidMask = ::MTL::StoreActionOptionValidMask;
using ColorWriteMask = ::MTL::ColorWriteMask;
inline constexpr auto ColorWriteMaskNone = ::MTL::ColorWriteMaskNone;
inline constexpr auto ColorWriteMaskRed = ::MTL::ColorWriteMaskRed;
inline constexpr auto ColorWriteMaskGreen = ::MTL::ColorWriteMaskGreen;
inline constexpr auto ColorWriteMaskBlue = ::MTL::ColorWriteMaskBlue;
inline constexpr auto ColorWriteMaskAlpha = ::MTL::ColorWriteMaskAlpha;
inline constexpr auto ColorWriteMaskAll = ::MTL::ColorWriteMaskAll;
inline constexpr auto ColorWriteMaskUnspecialized = ::MTL::ColorWriteMaskUnspecialized;
using ResourceOptions = ::MTL::ResourceOptions;
inline constexpr auto ResourceCPUCacheModeDefaultCache = ::MTL::ResourceCPUCacheModeDefaultCache;
inline constexpr auto ResourceCPUCacheModeWriteCombined = ::MTL::ResourceCPUCacheModeWriteCombined;
inline constexpr auto ResourceStorageModeShared = ::MTL::ResourceStorageModeShared;
inline constexpr auto ResourceStorageModeManaged = ::MTL::ResourceStorageModeManaged;
inline constexpr auto ResourceStorageModePrivate = ::MTL::ResourceStorageModePrivate;
inline constexpr auto ResourceStorageModeMemoryless = ::MTL::ResourceStorageModeMemoryless;
inline constexpr auto ResourceHazardTrackingModeDefault = ::MTL::ResourceHazardTrackingModeDefault;
inline constexpr auto ResourceHazardTrackingModeUntracked =
    ::MTL::ResourceHazardTrackingModeUntracked;
inline constexpr auto ResourceHazardTrackingModeTracked = ::MTL::ResourceHazardTrackingModeTracked;
using TensorUsage = ::MTL::TensorUsage;
inline constexpr auto TensorUsageCompute = ::MTL::TensorUsageCompute;
inline constexpr auto TensorUsageRender = ::MTL::TensorUsageRender;
inline constexpr auto TensorUsageMachineLearning = ::MTL::TensorUsageMachineLearning;
using TextureUsage = ::MTL::TextureUsage;
inline constexpr auto TextureUsageUnknown = ::MTL::TextureUsageUnknown;
inline constexpr auto TextureUsageShaderRead = ::MTL::TextureUsageShaderRead;
inline constexpr auto TextureUsageShaderWrite = ::MTL::TextureUsageShaderWrite;
inline constexpr auto TextureUsageRenderTarget = ::MTL::TextureUsageRenderTarget;
inline constexpr auto TextureUsagePixelFormatView = ::MTL::TextureUsagePixelFormatView;
inline constexpr auto TextureUsageShaderAtomic = ::MTL::TextureUsageShaderAtomic;

} // namespace cheatah::gpu::metal

// Metal 4 (`import gpu.metal4 as mtl4`) — the next-generation surface; its names overlap Metal 3's,
// so it lives in a parallel namespace.
namespace cheatah::gpu::metal4 {

using Archive = ::MTL4::Archive;
using ArgumentTableDescriptor = ::MTL4::ArgumentTableDescriptor;
using ArgumentTable = ::MTL4::ArgumentTable;
using BinaryFunctionDescriptor = ::MTL4::BinaryFunctionDescriptor;
using BinaryFunction = ::MTL4::BinaryFunction;
using CommandAllocatorDescriptor = ::MTL4::CommandAllocatorDescriptor;
using CommandAllocator = ::MTL4::CommandAllocator;
using CommandBufferOptions = ::MTL4::CommandBufferOptions;
using CommitOptions = ::MTL4::CommitOptions;
using CommitFeedback = ::MTL4::CommitFeedback;
using CompilerDescriptor = ::MTL4::CompilerDescriptor;
using CompilerTaskOptions = ::MTL4::CompilerTaskOptions;
using Compiler = ::MTL4::Compiler;
using CompilerTask = ::MTL4::CompilerTask;
using CounterHeapDescriptor = ::MTL4::CounterHeapDescriptor;
using CounterHeap = ::MTL4::CounterHeap;
using LibraryDescriptor = ::MTL4::LibraryDescriptor;
using LibraryFunctionDescriptor = ::MTL4::LibraryFunctionDescriptor;
using StaticLinkingDescriptor = ::MTL4::StaticLinkingDescriptor;
using PipelineStageDynamicLinkingDescriptor = ::MTL4::PipelineStageDynamicLinkingDescriptor;
using RenderPipelineDynamicLinkingDescriptor = ::MTL4::RenderPipelineDynamicLinkingDescriptor;
using MachineLearningCommandEncoder = ::MTL4::MachineLearningCommandEncoder;
using MachineLearningPipelineDescriptor = ::MTL4::MachineLearningPipelineDescriptor;
using MachineLearningPipelineReflection = ::MTL4::MachineLearningPipelineReflection;
using MachineLearningPipelineState = ::MTL4::MachineLearningPipelineState;
using PipelineDataSetSerializerDescriptor = ::MTL4::PipelineDataSetSerializerDescriptor;
using PipelineDataSetSerializer = ::MTL4::PipelineDataSetSerializer;
using PipelineOptions = ::MTL4::PipelineOptions;
using PipelineDescriptor = ::MTL4::PipelineDescriptor;
using RenderPipelineBinaryFunctionsDescriptor = ::MTL4::RenderPipelineBinaryFunctionsDescriptor;
using SpecializedFunctionDescriptor = ::MTL4::SpecializedFunctionDescriptor;
using StitchedFunctionDescriptor = ::MTL4::StitchedFunctionDescriptor;
using CommandQueueError = ::MTL4::CommandQueueError;
using CompilerTaskStatus = ::MTL4::CompilerTaskStatus;
using CounterHeapType = ::MTL4::CounterHeapType;
using TimestampGranularity = ::MTL4::TimestampGranularity;
using AlphaToOneState = ::MTL4::AlphaToOneState;
using AlphaToCoverageState = ::MTL4::AlphaToCoverageState;
using BlendState = ::MTL4::BlendState;
using IndirectCommandBufferSupportState = ::MTL4::IndirectCommandBufferSupportState;
using LogicalToPhysicalColorAttachmentMappingState =
    ::MTL4::LogicalToPhysicalColorAttachmentMappingState;
inline constexpr auto CommandQueueErrorNone = ::MTL4::CommandQueueErrorNone;
inline constexpr auto CommandQueueErrorTimeout = ::MTL4::CommandQueueErrorTimeout;
inline constexpr auto CommandQueueErrorNotPermitted = ::MTL4::CommandQueueErrorNotPermitted;
inline constexpr auto CommandQueueErrorOutOfMemory = ::MTL4::CommandQueueErrorOutOfMemory;
inline constexpr auto CommandQueueErrorDeviceRemoved = ::MTL4::CommandQueueErrorDeviceRemoved;
inline constexpr auto CommandQueueErrorAccessRevoked = ::MTL4::CommandQueueErrorAccessRevoked;
inline constexpr auto CommandQueueErrorInternal = ::MTL4::CommandQueueErrorInternal;
inline constexpr auto CompilerTaskStatusNone = ::MTL4::CompilerTaskStatusNone;
inline constexpr auto CompilerTaskStatusScheduled = ::MTL4::CompilerTaskStatusScheduled;
inline constexpr auto CompilerTaskStatusCompiling = ::MTL4::CompilerTaskStatusCompiling;
inline constexpr auto CompilerTaskStatusFinished = ::MTL4::CompilerTaskStatusFinished;
inline constexpr auto CounterHeapTypeInvalid = ::MTL4::CounterHeapTypeInvalid;
inline constexpr auto CounterHeapTypeTimestamp = ::MTL4::CounterHeapTypeTimestamp;
inline constexpr auto TimestampGranularityRelaxed = ::MTL4::TimestampGranularityRelaxed;
inline constexpr auto TimestampGranularityPrecise = ::MTL4::TimestampGranularityPrecise;
inline constexpr auto AlphaToOneStateDisabled = ::MTL4::AlphaToOneStateDisabled;
inline constexpr auto AlphaToOneStateEnabled = ::MTL4::AlphaToOneStateEnabled;
inline constexpr auto AlphaToCoverageStateDisabled = ::MTL4::AlphaToCoverageStateDisabled;
inline constexpr auto AlphaToCoverageStateEnabled = ::MTL4::AlphaToCoverageStateEnabled;
inline constexpr auto BlendStateDisabled = ::MTL4::BlendStateDisabled;
inline constexpr auto BlendStateEnabled = ::MTL4::BlendStateEnabled;
inline constexpr auto BlendStateUnspecialized = ::MTL4::BlendStateUnspecialized;
inline constexpr auto IndirectCommandBufferSupportStateDisabled =
    ::MTL4::IndirectCommandBufferSupportStateDisabled;
inline constexpr auto IndirectCommandBufferSupportStateEnabled =
    ::MTL4::IndirectCommandBufferSupportStateEnabled;
inline constexpr auto LogicalToPhysicalColorAttachmentMappingStateIdentity =
    ::MTL4::LogicalToPhysicalColorAttachmentMappingStateIdentity;
inline constexpr auto LogicalToPhysicalColorAttachmentMappingStateInherited =
    ::MTL4::LogicalToPhysicalColorAttachmentMappingStateInherited;
using BinaryFunctionOptions = ::MTL4::BinaryFunctionOptions;
using VisibilityOptions = ::MTL4::VisibilityOptions;
using PipelineDataSetSerializerConfiguration = ::MTL4::PipelineDataSetSerializerConfiguration;
using ShaderReflection = ::MTL4::ShaderReflection;
using RenderEncoderOptions = ::MTL4::RenderEncoderOptions;
inline constexpr auto BinaryFunctionOptionNone = ::MTL4::BinaryFunctionOptionNone;
inline constexpr auto BinaryFunctionOptionPipelineIndependent =
    ::MTL4::BinaryFunctionOptionPipelineIndependent;
inline constexpr auto VisibilityOptionNone = ::MTL4::VisibilityOptionNone;
inline constexpr auto VisibilityOptionDevice = ::MTL4::VisibilityOptionDevice;
inline constexpr auto VisibilityOptionResourceAlias = ::MTL4::VisibilityOptionResourceAlias;
inline constexpr auto PipelineDataSetSerializerConfigurationCaptureDescriptors =
    ::MTL4::PipelineDataSetSerializerConfigurationCaptureDescriptors;
inline constexpr auto PipelineDataSetSerializerConfigurationCaptureBinaries =
    ::MTL4::PipelineDataSetSerializerConfigurationCaptureBinaries;
inline constexpr auto ShaderReflectionNone = ::MTL4::ShaderReflectionNone;
inline constexpr auto ShaderReflectionBindingInfo = ::MTL4::ShaderReflectionBindingInfo;
inline constexpr auto ShaderReflectionBufferTypeInfo = ::MTL4::ShaderReflectionBufferTypeInfo;
inline constexpr auto RenderEncoderOptionNone = ::MTL4::RenderEncoderOptionNone;
inline constexpr auto RenderEncoderOptionSuspending = ::MTL4::RenderEncoderOptionSuspending;
inline constexpr auto RenderEncoderOptionResuming = ::MTL4::RenderEncoderOptionResuming;

} // namespace cheatah::gpu::metal4
