// GENERATED by tools/vulkan-gen/generate.purr from vk.xml — DO NOT EDIT.

// One TEST_F per forwarder (= 100% coverage of the generated surface), so each command is
// an individually-named, visible test. Each probes the real vk* entry point on every
// device via the VulkanPresence fixture (harness.hpp): capability-gated + NON-BLOCKING —
// a device lacking a feature is skipped, never a failure.

#include "harness.hpp"

namespace cheatah::gpu::vktest {

#ifdef VK_VERSION_1_0
TEST_F(VulkanPresence, CreateInstance) {
    probe("CreateInstance", (void**)&::vkCreateInstance, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyInstance) {
    probe("DestroyInstance", (void**)&::vkDestroyInstance, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EnumeratePhysicalDevices) {
    probe("EnumeratePhysicalDevices", (void**)&::vkEnumeratePhysicalDevices, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceFeatures) {
    probe("GetPhysicalDeviceFeatures", (void**)&::vkGetPhysicalDeviceFeatures, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceFormatProperties) {
    probe("GetPhysicalDeviceFormatProperties", (void**)&::vkGetPhysicalDeviceFormatProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceImageFormatProperties) {
    probe("GetPhysicalDeviceImageFormatProperties",
          (void**)&::vkGetPhysicalDeviceImageFormatProperties, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceProperties) {
    probe("GetPhysicalDeviceProperties", (void**)&::vkGetPhysicalDeviceProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceQueueFamilyProperties) {
    probe("GetPhysicalDeviceQueueFamilyProperties",
          (void**)&::vkGetPhysicalDeviceQueueFamilyProperties, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceMemoryProperties) {
    probe("GetPhysicalDeviceMemoryProperties", (void**)&::vkGetPhysicalDeviceMemoryProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetInstanceProcAddr) {
    probe("GetInstanceProcAddr", (void**)&::vkGetInstanceProcAddr, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetDeviceProcAddr) {
    probe("GetDeviceProcAddr", (void**)&::vkGetDeviceProcAddr, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateDevice) {
    probe("CreateDevice", (void**)&::vkCreateDevice, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyDevice) {
    probe("DestroyDevice", (void**)&::vkDestroyDevice, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EnumerateInstanceExtensionProperties) {
    probe("EnumerateInstanceExtensionProperties", (void**)&::vkEnumerateInstanceExtensionProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EnumerateDeviceExtensionProperties) {
    probe("EnumerateDeviceExtensionProperties", (void**)&::vkEnumerateDeviceExtensionProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EnumerateInstanceLayerProperties) {
    probe("EnumerateInstanceLayerProperties", (void**)&::vkEnumerateInstanceLayerProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EnumerateDeviceLayerProperties) {
    probe("EnumerateDeviceLayerProperties", (void**)&::vkEnumerateDeviceLayerProperties,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetDeviceQueue) {
    probe("GetDeviceQueue", (void**)&::vkGetDeviceQueue, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, QueueSubmit) {
    probe("QueueSubmit", (void**)&::vkQueueSubmit, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, QueueWaitIdle) {
    probe("QueueWaitIdle", (void**)&::vkQueueWaitIdle, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DeviceWaitIdle) {
    probe("DeviceWaitIdle", (void**)&::vkDeviceWaitIdle, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, AllocateMemory) {
    probe("AllocateMemory", (void**)&::vkAllocateMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, FreeMemory) {
    probe("FreeMemory", (void**)&::vkFreeMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, MapMemory) {
    probe("MapMemory", (void**)&::vkMapMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, UnmapMemory) {
    probe("UnmapMemory", (void**)&::vkUnmapMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, FlushMappedMemoryRanges) {
    probe("FlushMappedMemoryRanges", (void**)&::vkFlushMappedMemoryRanges, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, InvalidateMappedMemoryRanges) {
    probe("InvalidateMappedMemoryRanges", (void**)&::vkInvalidateMappedMemoryRanges,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetDeviceMemoryCommitment) {
    probe("GetDeviceMemoryCommitment", (void**)&::vkGetDeviceMemoryCommitment, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, BindBufferMemory) {
    probe("BindBufferMemory", (void**)&::vkBindBufferMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, BindImageMemory) {
    probe("BindImageMemory", (void**)&::vkBindImageMemory, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetBufferMemoryRequirements) {
    probe("GetBufferMemoryRequirements", (void**)&::vkGetBufferMemoryRequirements,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetImageMemoryRequirements) {
    probe("GetImageMemoryRequirements", (void**)&::vkGetImageMemoryRequirements,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetImageSparseMemoryRequirements) {
    probe("GetImageSparseMemoryRequirements", (void**)&::vkGetImageSparseMemoryRequirements,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPhysicalDeviceSparseImageFormatProperties) {
    probe("GetPhysicalDeviceSparseImageFormatProperties",
          (void**)&::vkGetPhysicalDeviceSparseImageFormatProperties, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, QueueBindSparse) {
    probe("QueueBindSparse", (void**)&::vkQueueBindSparse, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateFence) {
    probe("CreateFence", (void**)&::vkCreateFence, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyFence) {
    probe("DestroyFence", (void**)&::vkDestroyFence, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, ResetFences) {
    probe("ResetFences", (void**)&::vkResetFences, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetFenceStatus) {
    probe("GetFenceStatus", (void**)&::vkGetFenceStatus, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, WaitForFences) {
    probe("WaitForFences", (void**)&::vkWaitForFences, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateSemaphore) {
    probe("CreateSemaphore", (void**)&::vkCreateSemaphore, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroySemaphore) {
    probe("DestroySemaphore", (void**)&::vkDestroySemaphore, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateQueryPool) {
    probe("CreateQueryPool", (void**)&::vkCreateQueryPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyQueryPool) {
    probe("DestroyQueryPool", (void**)&::vkDestroyQueryPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetQueryPoolResults) {
    probe("GetQueryPoolResults", (void**)&::vkGetQueryPoolResults, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateBuffer) {
    probe("CreateBuffer", (void**)&::vkCreateBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyBuffer) {
    probe("DestroyBuffer", (void**)&::vkDestroyBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateImage) {
    probe("CreateImage", (void**)&::vkCreateImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyImage) {
    probe("DestroyImage", (void**)&::vkDestroyImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetImageSubresourceLayout) {
    probe("GetImageSubresourceLayout", (void**)&::vkGetImageSubresourceLayout, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateImageView) {
    probe("CreateImageView", (void**)&::vkCreateImageView, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyImageView) {
    probe("DestroyImageView", (void**)&::vkDestroyImageView, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateCommandPool) {
    probe("CreateCommandPool", (void**)&::vkCreateCommandPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyCommandPool) {
    probe("DestroyCommandPool", (void**)&::vkDestroyCommandPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, ResetCommandPool) {
    probe("ResetCommandPool", (void**)&::vkResetCommandPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, AllocateCommandBuffers) {
    probe("AllocateCommandBuffers", (void**)&::vkAllocateCommandBuffers, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, FreeCommandBuffers) {
    probe("FreeCommandBuffers", (void**)&::vkFreeCommandBuffers, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, BeginCommandBuffer) {
    probe("BeginCommandBuffer", (void**)&::vkBeginCommandBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, EndCommandBuffer) {
    probe("EndCommandBuffer", (void**)&::vkEndCommandBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, ResetCommandBuffer) {
    probe("ResetCommandBuffer", (void**)&::vkResetCommandBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdCopyBuffer) {
    probe("CmdCopyBuffer", (void**)&::vkCmdCopyBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdCopyImage) {
    probe("CmdCopyImage", (void**)&::vkCmdCopyImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdCopyBufferToImage) {
    probe("CmdCopyBufferToImage", (void**)&::vkCmdCopyBufferToImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdCopyImageToBuffer) {
    probe("CmdCopyImageToBuffer", (void**)&::vkCmdCopyImageToBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdUpdateBuffer) {
    probe("CmdUpdateBuffer", (void**)&::vkCmdUpdateBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdFillBuffer) {
    probe("CmdFillBuffer", (void**)&::vkCmdFillBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdPipelineBarrier) {
    probe("CmdPipelineBarrier", (void**)&::vkCmdPipelineBarrier, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBeginQuery) {
    probe("CmdBeginQuery", (void**)&::vkCmdBeginQuery, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdEndQuery) {
    probe("CmdEndQuery", (void**)&::vkCmdEndQuery, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdResetQueryPool) {
    probe("CmdResetQueryPool", (void**)&::vkCmdResetQueryPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdWriteTimestamp) {
    probe("CmdWriteTimestamp", (void**)&::vkCmdWriteTimestamp, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdCopyQueryPoolResults) {
    probe("CmdCopyQueryPoolResults", (void**)&::vkCmdCopyQueryPoolResults, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdExecuteCommands) {
    probe("CmdExecuteCommands", (void**)&::vkCmdExecuteCommands, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateEvent) {
    probe("CreateEvent", (void**)&::vkCreateEvent, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyEvent) {
    probe("DestroyEvent", (void**)&::vkDestroyEvent, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetEventStatus) {
    probe("GetEventStatus", (void**)&::vkGetEventStatus, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, SetEvent) { probe("SetEvent", (void**)&::vkSetEvent, VK_API_VERSION_1_0); }
TEST_F(VulkanPresence, ResetEvent) {
    probe("ResetEvent", (void**)&::vkResetEvent, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateBufferView) {
    probe("CreateBufferView", (void**)&::vkCreateBufferView, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyBufferView) {
    probe("DestroyBufferView", (void**)&::vkDestroyBufferView, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateShaderModule) {
    probe("CreateShaderModule", (void**)&::vkCreateShaderModule, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyShaderModule) {
    probe("DestroyShaderModule", (void**)&::vkDestroyShaderModule, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreatePipelineCache) {
    probe("CreatePipelineCache", (void**)&::vkCreatePipelineCache, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyPipelineCache) {
    probe("DestroyPipelineCache", (void**)&::vkDestroyPipelineCache, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetPipelineCacheData) {
    probe("GetPipelineCacheData", (void**)&::vkGetPipelineCacheData, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, MergePipelineCaches) {
    probe("MergePipelineCaches", (void**)&::vkMergePipelineCaches, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateComputePipelines) {
    probe("CreateComputePipelines", (void**)&::vkCreateComputePipelines, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyPipeline) {
    probe("DestroyPipeline", (void**)&::vkDestroyPipeline, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreatePipelineLayout) {
    probe("CreatePipelineLayout", (void**)&::vkCreatePipelineLayout, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyPipelineLayout) {
    probe("DestroyPipelineLayout", (void**)&::vkDestroyPipelineLayout, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateSampler) {
    probe("CreateSampler", (void**)&::vkCreateSampler, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroySampler) {
    probe("DestroySampler", (void**)&::vkDestroySampler, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateDescriptorSetLayout) {
    probe("CreateDescriptorSetLayout", (void**)&::vkCreateDescriptorSetLayout, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyDescriptorSetLayout) {
    probe("DestroyDescriptorSetLayout", (void**)&::vkDestroyDescriptorSetLayout,
          VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateDescriptorPool) {
    probe("CreateDescriptorPool", (void**)&::vkCreateDescriptorPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyDescriptorPool) {
    probe("DestroyDescriptorPool", (void**)&::vkDestroyDescriptorPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, ResetDescriptorPool) {
    probe("ResetDescriptorPool", (void**)&::vkResetDescriptorPool, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, AllocateDescriptorSets) {
    probe("AllocateDescriptorSets", (void**)&::vkAllocateDescriptorSets, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, FreeDescriptorSets) {
    probe("FreeDescriptorSets", (void**)&::vkFreeDescriptorSets, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, UpdateDescriptorSets) {
    probe("UpdateDescriptorSets", (void**)&::vkUpdateDescriptorSets, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBindPipeline) {
    probe("CmdBindPipeline", (void**)&::vkCmdBindPipeline, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBindDescriptorSets) {
    probe("CmdBindDescriptorSets", (void**)&::vkCmdBindDescriptorSets, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdClearColorImage) {
    probe("CmdClearColorImage", (void**)&::vkCmdClearColorImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdDispatch) {
    probe("CmdDispatch", (void**)&::vkCmdDispatch, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdDispatchIndirect) {
    probe("CmdDispatchIndirect", (void**)&::vkCmdDispatchIndirect, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetEvent) {
    probe("CmdSetEvent", (void**)&::vkCmdSetEvent, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdResetEvent) {
    probe("CmdResetEvent", (void**)&::vkCmdResetEvent, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdWaitEvents) {
    probe("CmdWaitEvents", (void**)&::vkCmdWaitEvents, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdPushConstants) {
    probe("CmdPushConstants", (void**)&::vkCmdPushConstants, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateGraphicsPipelines) {
    probe("CreateGraphicsPipelines", (void**)&::vkCreateGraphicsPipelines, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateFramebuffer) {
    probe("CreateFramebuffer", (void**)&::vkCreateFramebuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyFramebuffer) {
    probe("DestroyFramebuffer", (void**)&::vkDestroyFramebuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CreateRenderPass) {
    probe("CreateRenderPass", (void**)&::vkCreateRenderPass, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, DestroyRenderPass) {
    probe("DestroyRenderPass", (void**)&::vkDestroyRenderPass, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, GetRenderAreaGranularity) {
    probe("GetRenderAreaGranularity", (void**)&::vkGetRenderAreaGranularity, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetViewport) {
    probe("CmdSetViewport", (void**)&::vkCmdSetViewport, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetScissor) {
    probe("CmdSetScissor", (void**)&::vkCmdSetScissor, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetLineWidth) {
    probe("CmdSetLineWidth", (void**)&::vkCmdSetLineWidth, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetDepthBias) {
    probe("CmdSetDepthBias", (void**)&::vkCmdSetDepthBias, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetBlendConstants) {
    probe("CmdSetBlendConstants", (void**)&::vkCmdSetBlendConstants, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetDepthBounds) {
    probe("CmdSetDepthBounds", (void**)&::vkCmdSetDepthBounds, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetStencilCompareMask) {
    probe("CmdSetStencilCompareMask", (void**)&::vkCmdSetStencilCompareMask, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetStencilWriteMask) {
    probe("CmdSetStencilWriteMask", (void**)&::vkCmdSetStencilWriteMask, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdSetStencilReference) {
    probe("CmdSetStencilReference", (void**)&::vkCmdSetStencilReference, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBindIndexBuffer) {
    probe("CmdBindIndexBuffer", (void**)&::vkCmdBindIndexBuffer, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBindVertexBuffers) {
    probe("CmdBindVertexBuffers", (void**)&::vkCmdBindVertexBuffers, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdDraw) { probe("CmdDraw", (void**)&::vkCmdDraw, VK_API_VERSION_1_0); }
TEST_F(VulkanPresence, CmdDrawIndexed) {
    probe("CmdDrawIndexed", (void**)&::vkCmdDrawIndexed, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdDrawIndirect) {
    probe("CmdDrawIndirect", (void**)&::vkCmdDrawIndirect, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdDrawIndexedIndirect) {
    probe("CmdDrawIndexedIndirect", (void**)&::vkCmdDrawIndexedIndirect, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBlitImage) {
    probe("CmdBlitImage", (void**)&::vkCmdBlitImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdClearDepthStencilImage) {
    probe("CmdClearDepthStencilImage", (void**)&::vkCmdClearDepthStencilImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdClearAttachments) {
    probe("CmdClearAttachments", (void**)&::vkCmdClearAttachments, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdResolveImage) {
    probe("CmdResolveImage", (void**)&::vkCmdResolveImage, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdBeginRenderPass) {
    probe("CmdBeginRenderPass", (void**)&::vkCmdBeginRenderPass, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdNextSubpass) {
    probe("CmdNextSubpass", (void**)&::vkCmdNextSubpass, VK_API_VERSION_1_0);
}
TEST_F(VulkanPresence, CmdEndRenderPass) {
    probe("CmdEndRenderPass", (void**)&::vkCmdEndRenderPass, VK_API_VERSION_1_0);
}
#endif
#ifdef VK_VERSION_1_1
TEST_F(VulkanPresence, EnumerateInstanceVersion) {
    probe("EnumerateInstanceVersion", (void**)&::vkEnumerateInstanceVersion, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, BindBufferMemory2) {
    probe("BindBufferMemory2", (void**)&::vkBindBufferMemory2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, BindImageMemory2) {
    probe("BindImageMemory2", (void**)&::vkBindImageMemory2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetDeviceGroupPeerMemoryFeatures) {
    probe("GetDeviceGroupPeerMemoryFeatures", (void**)&::vkGetDeviceGroupPeerMemoryFeatures,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, CmdSetDeviceMask) {
    probe("CmdSetDeviceMask", (void**)&::vkCmdSetDeviceMask, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, EnumeratePhysicalDeviceGroups) {
    probe("EnumeratePhysicalDeviceGroups", (void**)&::vkEnumeratePhysicalDeviceGroups,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetImageMemoryRequirements2) {
    probe("GetImageMemoryRequirements2", (void**)&::vkGetImageMemoryRequirements2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetBufferMemoryRequirements2) {
    probe("GetBufferMemoryRequirements2", (void**)&::vkGetBufferMemoryRequirements2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetImageSparseMemoryRequirements2) {
    probe("GetImageSparseMemoryRequirements2", (void**)&::vkGetImageSparseMemoryRequirements2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceFeatures2) {
    probe("GetPhysicalDeviceFeatures2", (void**)&::vkGetPhysicalDeviceFeatures2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceProperties2) {
    probe("GetPhysicalDeviceProperties2", (void**)&::vkGetPhysicalDeviceProperties2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceFormatProperties2) {
    probe("GetPhysicalDeviceFormatProperties2", (void**)&::vkGetPhysicalDeviceFormatProperties2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceImageFormatProperties2) {
    probe("GetPhysicalDeviceImageFormatProperties2",
          (void**)&::vkGetPhysicalDeviceImageFormatProperties2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceQueueFamilyProperties2) {
    probe("GetPhysicalDeviceQueueFamilyProperties2",
          (void**)&::vkGetPhysicalDeviceQueueFamilyProperties2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceMemoryProperties2) {
    probe("GetPhysicalDeviceMemoryProperties2", (void**)&::vkGetPhysicalDeviceMemoryProperties2,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceSparseImageFormatProperties2) {
    probe("GetPhysicalDeviceSparseImageFormatProperties2",
          (void**)&::vkGetPhysicalDeviceSparseImageFormatProperties2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, TrimCommandPool) {
    probe("TrimCommandPool", (void**)&::vkTrimCommandPool, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetDeviceQueue2) {
    probe("GetDeviceQueue2", (void**)&::vkGetDeviceQueue2, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceExternalBufferProperties) {
    probe("GetPhysicalDeviceExternalBufferProperties",
          (void**)&::vkGetPhysicalDeviceExternalBufferProperties, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceExternalFenceProperties) {
    probe("GetPhysicalDeviceExternalFenceProperties",
          (void**)&::vkGetPhysicalDeviceExternalFenceProperties, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetPhysicalDeviceExternalSemaphoreProperties) {
    probe("GetPhysicalDeviceExternalSemaphoreProperties",
          (void**)&::vkGetPhysicalDeviceExternalSemaphoreProperties, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, CmdDispatchBase) {
    probe("CmdDispatchBase", (void**)&::vkCmdDispatchBase, VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, CreateDescriptorUpdateTemplate) {
    probe("CreateDescriptorUpdateTemplate", (void**)&::vkCreateDescriptorUpdateTemplate,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, DestroyDescriptorUpdateTemplate) {
    probe("DestroyDescriptorUpdateTemplate", (void**)&::vkDestroyDescriptorUpdateTemplate,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, UpdateDescriptorSetWithTemplate) {
    probe("UpdateDescriptorSetWithTemplate", (void**)&::vkUpdateDescriptorSetWithTemplate,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, GetDescriptorSetLayoutSupport) {
    probe("GetDescriptorSetLayoutSupport", (void**)&::vkGetDescriptorSetLayoutSupport,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, CreateSamplerYcbcrConversion) {
    probe("CreateSamplerYcbcrConversion", (void**)&::vkCreateSamplerYcbcrConversion,
          VK_API_VERSION_1_1);
}
TEST_F(VulkanPresence, DestroySamplerYcbcrConversion) {
    probe("DestroySamplerYcbcrConversion", (void**)&::vkDestroySamplerYcbcrConversion,
          VK_API_VERSION_1_1);
}
#endif
#ifdef VK_VERSION_1_2
TEST_F(VulkanPresence, ResetQueryPool) {
    probe("ResetQueryPool", (void**)&::vkResetQueryPool, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, GetSemaphoreCounterValue) {
    probe("GetSemaphoreCounterValue", (void**)&::vkGetSemaphoreCounterValue, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, WaitSemaphores) {
    probe("WaitSemaphores", (void**)&::vkWaitSemaphores, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, SignalSemaphore) {
    probe("SignalSemaphore", (void**)&::vkSignalSemaphore, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, GetBufferDeviceAddress) {
    probe("GetBufferDeviceAddress", (void**)&::vkGetBufferDeviceAddress, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, GetBufferOpaqueCaptureAddress) {
    probe("GetBufferOpaqueCaptureAddress", (void**)&::vkGetBufferOpaqueCaptureAddress,
          VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, GetDeviceMemoryOpaqueCaptureAddress) {
    probe("GetDeviceMemoryOpaqueCaptureAddress", (void**)&::vkGetDeviceMemoryOpaqueCaptureAddress,
          VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CmdDrawIndirectCount) {
    probe("CmdDrawIndirectCount", (void**)&::vkCmdDrawIndirectCount, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CmdDrawIndexedIndirectCount) {
    probe("CmdDrawIndexedIndirectCount", (void**)&::vkCmdDrawIndexedIndirectCount,
          VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CreateRenderPass2) {
    probe("CreateRenderPass2", (void**)&::vkCreateRenderPass2, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CmdBeginRenderPass2) {
    probe("CmdBeginRenderPass2", (void**)&::vkCmdBeginRenderPass2, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CmdNextSubpass2) {
    probe("CmdNextSubpass2", (void**)&::vkCmdNextSubpass2, VK_API_VERSION_1_2);
}
TEST_F(VulkanPresence, CmdEndRenderPass2) {
    probe("CmdEndRenderPass2", (void**)&::vkCmdEndRenderPass2, VK_API_VERSION_1_2);
}
#endif
#ifdef VK_VERSION_1_3
TEST_F(VulkanPresence, GetPhysicalDeviceToolProperties) {
    probe("GetPhysicalDeviceToolProperties", (void**)&::vkGetPhysicalDeviceToolProperties,
          VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CreatePrivateDataSlot) {
    probe("CreatePrivateDataSlot", (void**)&::vkCreatePrivateDataSlot, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, DestroyPrivateDataSlot) {
    probe("DestroyPrivateDataSlot", (void**)&::vkDestroyPrivateDataSlot, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, SetPrivateData) {
    probe("SetPrivateData", (void**)&::vkSetPrivateData, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, GetPrivateData) {
    probe("GetPrivateData", (void**)&::vkGetPrivateData, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdPipelineBarrier2) {
    probe("CmdPipelineBarrier2", (void**)&::vkCmdPipelineBarrier2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdWriteTimestamp2) {
    probe("CmdWriteTimestamp2", (void**)&::vkCmdWriteTimestamp2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, QueueSubmit2) {
    probe("QueueSubmit2", (void**)&::vkQueueSubmit2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdCopyBuffer2) {
    probe("CmdCopyBuffer2", (void**)&::vkCmdCopyBuffer2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdCopyImage2) {
    probe("CmdCopyImage2", (void**)&::vkCmdCopyImage2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdCopyBufferToImage2) {
    probe("CmdCopyBufferToImage2", (void**)&::vkCmdCopyBufferToImage2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdCopyImageToBuffer2) {
    probe("CmdCopyImageToBuffer2", (void**)&::vkCmdCopyImageToBuffer2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, GetDeviceBufferMemoryRequirements) {
    probe("GetDeviceBufferMemoryRequirements", (void**)&::vkGetDeviceBufferMemoryRequirements,
          VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, GetDeviceImageMemoryRequirements) {
    probe("GetDeviceImageMemoryRequirements", (void**)&::vkGetDeviceImageMemoryRequirements,
          VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, GetDeviceImageSparseMemoryRequirements) {
    probe("GetDeviceImageSparseMemoryRequirements",
          (void**)&::vkGetDeviceImageSparseMemoryRequirements, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetEvent2) {
    probe("CmdSetEvent2", (void**)&::vkCmdSetEvent2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdResetEvent2) {
    probe("CmdResetEvent2", (void**)&::vkCmdResetEvent2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdWaitEvents2) {
    probe("CmdWaitEvents2", (void**)&::vkCmdWaitEvents2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdBlitImage2) {
    probe("CmdBlitImage2", (void**)&::vkCmdBlitImage2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdResolveImage2) {
    probe("CmdResolveImage2", (void**)&::vkCmdResolveImage2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdBeginRendering) {
    probe("CmdBeginRendering", (void**)&::vkCmdBeginRendering, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdEndRendering) {
    probe("CmdEndRendering", (void**)&::vkCmdEndRendering, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetCullMode) {
    probe("CmdSetCullMode", (void**)&::vkCmdSetCullMode, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetFrontFace) {
    probe("CmdSetFrontFace", (void**)&::vkCmdSetFrontFace, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetPrimitiveTopology) {
    probe("CmdSetPrimitiveTopology", (void**)&::vkCmdSetPrimitiveTopology, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetViewportWithCount) {
    probe("CmdSetViewportWithCount", (void**)&::vkCmdSetViewportWithCount, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetScissorWithCount) {
    probe("CmdSetScissorWithCount", (void**)&::vkCmdSetScissorWithCount, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdBindVertexBuffers2) {
    probe("CmdBindVertexBuffers2", (void**)&::vkCmdBindVertexBuffers2, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetDepthTestEnable) {
    probe("CmdSetDepthTestEnable", (void**)&::vkCmdSetDepthTestEnable, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetDepthWriteEnable) {
    probe("CmdSetDepthWriteEnable", (void**)&::vkCmdSetDepthWriteEnable, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetDepthCompareOp) {
    probe("CmdSetDepthCompareOp", (void**)&::vkCmdSetDepthCompareOp, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetDepthBoundsTestEnable) {
    probe("CmdSetDepthBoundsTestEnable", (void**)&::vkCmdSetDepthBoundsTestEnable,
          VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetStencilTestEnable) {
    probe("CmdSetStencilTestEnable", (void**)&::vkCmdSetStencilTestEnable, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetStencilOp) {
    probe("CmdSetStencilOp", (void**)&::vkCmdSetStencilOp, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetRasterizerDiscardEnable) {
    probe("CmdSetRasterizerDiscardEnable", (void**)&::vkCmdSetRasterizerDiscardEnable,
          VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetDepthBiasEnable) {
    probe("CmdSetDepthBiasEnable", (void**)&::vkCmdSetDepthBiasEnable, VK_API_VERSION_1_3);
}
TEST_F(VulkanPresence, CmdSetPrimitiveRestartEnable) {
    probe("CmdSetPrimitiveRestartEnable", (void**)&::vkCmdSetPrimitiveRestartEnable,
          VK_API_VERSION_1_3);
}
#endif
#ifdef VK_VERSION_1_4
TEST_F(VulkanPresence, MapMemory2) {
    probe("MapMemory2", (void**)&::vkMapMemory2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, UnmapMemory2) {
    probe("UnmapMemory2", (void**)&::vkUnmapMemory2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, GetDeviceImageSubresourceLayout) {
    probe("GetDeviceImageSubresourceLayout", (void**)&::vkGetDeviceImageSubresourceLayout,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, GetImageSubresourceLayout2) {
    probe("GetImageSubresourceLayout2", (void**)&::vkGetImageSubresourceLayout2,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CopyMemoryToImage) {
    probe("CopyMemoryToImage", (void**)&::vkCopyMemoryToImage, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CopyImageToMemory) {
    probe("CopyImageToMemory", (void**)&::vkCopyImageToMemory, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CopyImageToImage) {
    probe("CopyImageToImage", (void**)&::vkCopyImageToImage, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, TransitionImageLayout) {
    probe("TransitionImageLayout", (void**)&::vkTransitionImageLayout, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdPushDescriptorSet) {
    probe("CmdPushDescriptorSet", (void**)&::vkCmdPushDescriptorSet, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdPushDescriptorSetWithTemplate) {
    probe("CmdPushDescriptorSetWithTemplate", (void**)&::vkCmdPushDescriptorSetWithTemplate,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdBindDescriptorSets2) {
    probe("CmdBindDescriptorSets2", (void**)&::vkCmdBindDescriptorSets2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdPushConstants2) {
    probe("CmdPushConstants2", (void**)&::vkCmdPushConstants2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdPushDescriptorSet2) {
    probe("CmdPushDescriptorSet2", (void**)&::vkCmdPushDescriptorSet2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdPushDescriptorSetWithTemplate2) {
    probe("CmdPushDescriptorSetWithTemplate2", (void**)&::vkCmdPushDescriptorSetWithTemplate2,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdSetLineStipple) {
    probe("CmdSetLineStipple", (void**)&::vkCmdSetLineStipple, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdBindIndexBuffer2) {
    probe("CmdBindIndexBuffer2", (void**)&::vkCmdBindIndexBuffer2, VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, GetRenderingAreaGranularity) {
    probe("GetRenderingAreaGranularity", (void**)&::vkGetRenderingAreaGranularity,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdSetRenderingAttachmentLocations) {
    probe("CmdSetRenderingAttachmentLocations", (void**)&::vkCmdSetRenderingAttachmentLocations,
          VK_API_VERSION_1_4);
}
TEST_F(VulkanPresence, CmdSetRenderingInputAttachmentIndices) {
    probe("CmdSetRenderingInputAttachmentIndices",
          (void**)&::vkCmdSetRenderingInputAttachmentIndices, VK_API_VERSION_1_4);
}
#endif

} // namespace cheatah::gpu::vktest
