// GENERATED by tools/vulkan-gen/generate.purr from vk.xml — DO NOT EDIT.

// One presence check per forwarder (= 100% coverage of the generated surface): the real
// vk* entry point must load on each device whose Vulkan version covers it. Capability-gated
// by the harness, so a device lacking a feature SKIPS — it never fails the gate.

#include "harness.hpp"

namespace cheatah::gpu::vktest {

void run_generated_presence_checks(const Device& d) {
#ifdef VK_VERSION_1_0
    check(d, "CreateInstance", (void*)::vkCreateInstance, VK_API_VERSION_1_0);
    check(d, "DestroyInstance", (void*)::vkDestroyInstance, VK_API_VERSION_1_0);
    check(d, "EnumeratePhysicalDevices", (void*)::vkEnumeratePhysicalDevices, VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceFeatures", (void*)::vkGetPhysicalDeviceFeatures, VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceFormatProperties", (void*)::vkGetPhysicalDeviceFormatProperties,
          VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceImageFormatProperties",
          (void*)::vkGetPhysicalDeviceImageFormatProperties, VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceProperties", (void*)::vkGetPhysicalDeviceProperties,
          VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceQueueFamilyProperties",
          (void*)::vkGetPhysicalDeviceQueueFamilyProperties, VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceMemoryProperties", (void*)::vkGetPhysicalDeviceMemoryProperties,
          VK_API_VERSION_1_0);
    check(d, "GetInstanceProcAddr", (void*)::vkGetInstanceProcAddr, VK_API_VERSION_1_0);
    check(d, "GetDeviceProcAddr", (void*)::vkGetDeviceProcAddr, VK_API_VERSION_1_0);
    check(d, "CreateDevice", (void*)::vkCreateDevice, VK_API_VERSION_1_0);
    check(d, "DestroyDevice", (void*)::vkDestroyDevice, VK_API_VERSION_1_0);
    check(d, "EnumerateInstanceExtensionProperties",
          (void*)::vkEnumerateInstanceExtensionProperties, VK_API_VERSION_1_0);
    check(d, "EnumerateDeviceExtensionProperties", (void*)::vkEnumerateDeviceExtensionProperties,
          VK_API_VERSION_1_0);
    check(d, "EnumerateInstanceLayerProperties", (void*)::vkEnumerateInstanceLayerProperties,
          VK_API_VERSION_1_0);
    check(d, "EnumerateDeviceLayerProperties", (void*)::vkEnumerateDeviceLayerProperties,
          VK_API_VERSION_1_0);
    check(d, "GetDeviceQueue", (void*)::vkGetDeviceQueue, VK_API_VERSION_1_0);
    check(d, "QueueSubmit", (void*)::vkQueueSubmit, VK_API_VERSION_1_0);
    check(d, "QueueWaitIdle", (void*)::vkQueueWaitIdle, VK_API_VERSION_1_0);
    check(d, "DeviceWaitIdle", (void*)::vkDeviceWaitIdle, VK_API_VERSION_1_0);
    check(d, "AllocateMemory", (void*)::vkAllocateMemory, VK_API_VERSION_1_0);
    check(d, "FreeMemory", (void*)::vkFreeMemory, VK_API_VERSION_1_0);
    check(d, "MapMemory", (void*)::vkMapMemory, VK_API_VERSION_1_0);
    check(d, "UnmapMemory", (void*)::vkUnmapMemory, VK_API_VERSION_1_0);
    check(d, "FlushMappedMemoryRanges", (void*)::vkFlushMappedMemoryRanges, VK_API_VERSION_1_0);
    check(d, "InvalidateMappedMemoryRanges", (void*)::vkInvalidateMappedMemoryRanges,
          VK_API_VERSION_1_0);
    check(d, "GetDeviceMemoryCommitment", (void*)::vkGetDeviceMemoryCommitment, VK_API_VERSION_1_0);
    check(d, "BindBufferMemory", (void*)::vkBindBufferMemory, VK_API_VERSION_1_0);
    check(d, "BindImageMemory", (void*)::vkBindImageMemory, VK_API_VERSION_1_0);
    check(d, "GetBufferMemoryRequirements", (void*)::vkGetBufferMemoryRequirements,
          VK_API_VERSION_1_0);
    check(d, "GetImageMemoryRequirements", (void*)::vkGetImageMemoryRequirements,
          VK_API_VERSION_1_0);
    check(d, "GetImageSparseMemoryRequirements", (void*)::vkGetImageSparseMemoryRequirements,
          VK_API_VERSION_1_0);
    check(d, "GetPhysicalDeviceSparseImageFormatProperties",
          (void*)::vkGetPhysicalDeviceSparseImageFormatProperties, VK_API_VERSION_1_0);
    check(d, "QueueBindSparse", (void*)::vkQueueBindSparse, VK_API_VERSION_1_0);
    check(d, "CreateFence", (void*)::vkCreateFence, VK_API_VERSION_1_0);
    check(d, "DestroyFence", (void*)::vkDestroyFence, VK_API_VERSION_1_0);
    check(d, "ResetFences", (void*)::vkResetFences, VK_API_VERSION_1_0);
    check(d, "GetFenceStatus", (void*)::vkGetFenceStatus, VK_API_VERSION_1_0);
    check(d, "WaitForFences", (void*)::vkWaitForFences, VK_API_VERSION_1_0);
    check(d, "CreateSemaphore", (void*)::vkCreateSemaphore, VK_API_VERSION_1_0);
    check(d, "DestroySemaphore", (void*)::vkDestroySemaphore, VK_API_VERSION_1_0);
    check(d, "CreateQueryPool", (void*)::vkCreateQueryPool, VK_API_VERSION_1_0);
    check(d, "DestroyQueryPool", (void*)::vkDestroyQueryPool, VK_API_VERSION_1_0);
    check(d, "GetQueryPoolResults", (void*)::vkGetQueryPoolResults, VK_API_VERSION_1_0);
    check(d, "CreateBuffer", (void*)::vkCreateBuffer, VK_API_VERSION_1_0);
    check(d, "DestroyBuffer", (void*)::vkDestroyBuffer, VK_API_VERSION_1_0);
    check(d, "CreateImage", (void*)::vkCreateImage, VK_API_VERSION_1_0);
    check(d, "DestroyImage", (void*)::vkDestroyImage, VK_API_VERSION_1_0);
    check(d, "GetImageSubresourceLayout", (void*)::vkGetImageSubresourceLayout, VK_API_VERSION_1_0);
    check(d, "CreateImageView", (void*)::vkCreateImageView, VK_API_VERSION_1_0);
    check(d, "DestroyImageView", (void*)::vkDestroyImageView, VK_API_VERSION_1_0);
    check(d, "CreateCommandPool", (void*)::vkCreateCommandPool, VK_API_VERSION_1_0);
    check(d, "DestroyCommandPool", (void*)::vkDestroyCommandPool, VK_API_VERSION_1_0);
    check(d, "ResetCommandPool", (void*)::vkResetCommandPool, VK_API_VERSION_1_0);
    check(d, "AllocateCommandBuffers", (void*)::vkAllocateCommandBuffers, VK_API_VERSION_1_0);
    check(d, "FreeCommandBuffers", (void*)::vkFreeCommandBuffers, VK_API_VERSION_1_0);
    check(d, "BeginCommandBuffer", (void*)::vkBeginCommandBuffer, VK_API_VERSION_1_0);
    check(d, "EndCommandBuffer", (void*)::vkEndCommandBuffer, VK_API_VERSION_1_0);
    check(d, "ResetCommandBuffer", (void*)::vkResetCommandBuffer, VK_API_VERSION_1_0);
    check(d, "CmdCopyBuffer", (void*)::vkCmdCopyBuffer, VK_API_VERSION_1_0);
    check(d, "CmdCopyImage", (void*)::vkCmdCopyImage, VK_API_VERSION_1_0);
    check(d, "CmdCopyBufferToImage", (void*)::vkCmdCopyBufferToImage, VK_API_VERSION_1_0);
    check(d, "CmdCopyImageToBuffer", (void*)::vkCmdCopyImageToBuffer, VK_API_VERSION_1_0);
    check(d, "CmdUpdateBuffer", (void*)::vkCmdUpdateBuffer, VK_API_VERSION_1_0);
    check(d, "CmdFillBuffer", (void*)::vkCmdFillBuffer, VK_API_VERSION_1_0);
    check(d, "CmdPipelineBarrier", (void*)::vkCmdPipelineBarrier, VK_API_VERSION_1_0);
    check(d, "CmdBeginQuery", (void*)::vkCmdBeginQuery, VK_API_VERSION_1_0);
    check(d, "CmdEndQuery", (void*)::vkCmdEndQuery, VK_API_VERSION_1_0);
    check(d, "CmdResetQueryPool", (void*)::vkCmdResetQueryPool, VK_API_VERSION_1_0);
    check(d, "CmdWriteTimestamp", (void*)::vkCmdWriteTimestamp, VK_API_VERSION_1_0);
    check(d, "CmdCopyQueryPoolResults", (void*)::vkCmdCopyQueryPoolResults, VK_API_VERSION_1_0);
    check(d, "CmdExecuteCommands", (void*)::vkCmdExecuteCommands, VK_API_VERSION_1_0);
    check(d, "CreateEvent", (void*)::vkCreateEvent, VK_API_VERSION_1_0);
    check(d, "DestroyEvent", (void*)::vkDestroyEvent, VK_API_VERSION_1_0);
    check(d, "GetEventStatus", (void*)::vkGetEventStatus, VK_API_VERSION_1_0);
    check(d, "SetEvent", (void*)::vkSetEvent, VK_API_VERSION_1_0);
    check(d, "ResetEvent", (void*)::vkResetEvent, VK_API_VERSION_1_0);
    check(d, "CreateBufferView", (void*)::vkCreateBufferView, VK_API_VERSION_1_0);
    check(d, "DestroyBufferView", (void*)::vkDestroyBufferView, VK_API_VERSION_1_0);
    check(d, "CreateShaderModule", (void*)::vkCreateShaderModule, VK_API_VERSION_1_0);
    check(d, "DestroyShaderModule", (void*)::vkDestroyShaderModule, VK_API_VERSION_1_0);
    check(d, "CreatePipelineCache", (void*)::vkCreatePipelineCache, VK_API_VERSION_1_0);
    check(d, "DestroyPipelineCache", (void*)::vkDestroyPipelineCache, VK_API_VERSION_1_0);
    check(d, "GetPipelineCacheData", (void*)::vkGetPipelineCacheData, VK_API_VERSION_1_0);
    check(d, "MergePipelineCaches", (void*)::vkMergePipelineCaches, VK_API_VERSION_1_0);
    check(d, "CreateComputePipelines", (void*)::vkCreateComputePipelines, VK_API_VERSION_1_0);
    check(d, "DestroyPipeline", (void*)::vkDestroyPipeline, VK_API_VERSION_1_0);
    check(d, "CreatePipelineLayout", (void*)::vkCreatePipelineLayout, VK_API_VERSION_1_0);
    check(d, "DestroyPipelineLayout", (void*)::vkDestroyPipelineLayout, VK_API_VERSION_1_0);
    check(d, "CreateSampler", (void*)::vkCreateSampler, VK_API_VERSION_1_0);
    check(d, "DestroySampler", (void*)::vkDestroySampler, VK_API_VERSION_1_0);
    check(d, "CreateDescriptorSetLayout", (void*)::vkCreateDescriptorSetLayout, VK_API_VERSION_1_0);
    check(d, "DestroyDescriptorSetLayout", (void*)::vkDestroyDescriptorSetLayout,
          VK_API_VERSION_1_0);
    check(d, "CreateDescriptorPool", (void*)::vkCreateDescriptorPool, VK_API_VERSION_1_0);
    check(d, "DestroyDescriptorPool", (void*)::vkDestroyDescriptorPool, VK_API_VERSION_1_0);
    check(d, "ResetDescriptorPool", (void*)::vkResetDescriptorPool, VK_API_VERSION_1_0);
    check(d, "AllocateDescriptorSets", (void*)::vkAllocateDescriptorSets, VK_API_VERSION_1_0);
    check(d, "FreeDescriptorSets", (void*)::vkFreeDescriptorSets, VK_API_VERSION_1_0);
    check(d, "UpdateDescriptorSets", (void*)::vkUpdateDescriptorSets, VK_API_VERSION_1_0);
    check(d, "CmdBindPipeline", (void*)::vkCmdBindPipeline, VK_API_VERSION_1_0);
    check(d, "CmdBindDescriptorSets", (void*)::vkCmdBindDescriptorSets, VK_API_VERSION_1_0);
    check(d, "CmdClearColorImage", (void*)::vkCmdClearColorImage, VK_API_VERSION_1_0);
    check(d, "CmdDispatch", (void*)::vkCmdDispatch, VK_API_VERSION_1_0);
    check(d, "CmdDispatchIndirect", (void*)::vkCmdDispatchIndirect, VK_API_VERSION_1_0);
    check(d, "CmdSetEvent", (void*)::vkCmdSetEvent, VK_API_VERSION_1_0);
    check(d, "CmdResetEvent", (void*)::vkCmdResetEvent, VK_API_VERSION_1_0);
    check(d, "CmdWaitEvents", (void*)::vkCmdWaitEvents, VK_API_VERSION_1_0);
    check(d, "CmdPushConstants", (void*)::vkCmdPushConstants, VK_API_VERSION_1_0);
    check(d, "CreateGraphicsPipelines", (void*)::vkCreateGraphicsPipelines, VK_API_VERSION_1_0);
    check(d, "CreateFramebuffer", (void*)::vkCreateFramebuffer, VK_API_VERSION_1_0);
    check(d, "DestroyFramebuffer", (void*)::vkDestroyFramebuffer, VK_API_VERSION_1_0);
    check(d, "CreateRenderPass", (void*)::vkCreateRenderPass, VK_API_VERSION_1_0);
    check(d, "DestroyRenderPass", (void*)::vkDestroyRenderPass, VK_API_VERSION_1_0);
    check(d, "GetRenderAreaGranularity", (void*)::vkGetRenderAreaGranularity, VK_API_VERSION_1_0);
    check(d, "CmdSetViewport", (void*)::vkCmdSetViewport, VK_API_VERSION_1_0);
    check(d, "CmdSetScissor", (void*)::vkCmdSetScissor, VK_API_VERSION_1_0);
    check(d, "CmdSetLineWidth", (void*)::vkCmdSetLineWidth, VK_API_VERSION_1_0);
    check(d, "CmdSetDepthBias", (void*)::vkCmdSetDepthBias, VK_API_VERSION_1_0);
    check(d, "CmdSetBlendConstants", (void*)::vkCmdSetBlendConstants, VK_API_VERSION_1_0);
    check(d, "CmdSetDepthBounds", (void*)::vkCmdSetDepthBounds, VK_API_VERSION_1_0);
    check(d, "CmdSetStencilCompareMask", (void*)::vkCmdSetStencilCompareMask, VK_API_VERSION_1_0);
    check(d, "CmdSetStencilWriteMask", (void*)::vkCmdSetStencilWriteMask, VK_API_VERSION_1_0);
    check(d, "CmdSetStencilReference", (void*)::vkCmdSetStencilReference, VK_API_VERSION_1_0);
    check(d, "CmdBindIndexBuffer", (void*)::vkCmdBindIndexBuffer, VK_API_VERSION_1_0);
    check(d, "CmdBindVertexBuffers", (void*)::vkCmdBindVertexBuffers, VK_API_VERSION_1_0);
    check(d, "CmdDraw", (void*)::vkCmdDraw, VK_API_VERSION_1_0);
    check(d, "CmdDrawIndexed", (void*)::vkCmdDrawIndexed, VK_API_VERSION_1_0);
    check(d, "CmdDrawIndirect", (void*)::vkCmdDrawIndirect, VK_API_VERSION_1_0);
    check(d, "CmdDrawIndexedIndirect", (void*)::vkCmdDrawIndexedIndirect, VK_API_VERSION_1_0);
    check(d, "CmdBlitImage", (void*)::vkCmdBlitImage, VK_API_VERSION_1_0);
    check(d, "CmdClearDepthStencilImage", (void*)::vkCmdClearDepthStencilImage, VK_API_VERSION_1_0);
    check(d, "CmdClearAttachments", (void*)::vkCmdClearAttachments, VK_API_VERSION_1_0);
    check(d, "CmdResolveImage", (void*)::vkCmdResolveImage, VK_API_VERSION_1_0);
    check(d, "CmdBeginRenderPass", (void*)::vkCmdBeginRenderPass, VK_API_VERSION_1_0);
    check(d, "CmdNextSubpass", (void*)::vkCmdNextSubpass, VK_API_VERSION_1_0);
    check(d, "CmdEndRenderPass", (void*)::vkCmdEndRenderPass, VK_API_VERSION_1_0);
#endif
#ifdef VK_VERSION_1_1
    check(d, "EnumerateInstanceVersion", (void*)::vkEnumerateInstanceVersion, VK_API_VERSION_1_1);
    check(d, "BindBufferMemory2", (void*)::vkBindBufferMemory2, VK_API_VERSION_1_1);
    check(d, "BindImageMemory2", (void*)::vkBindImageMemory2, VK_API_VERSION_1_1);
    check(d, "GetDeviceGroupPeerMemoryFeatures", (void*)::vkGetDeviceGroupPeerMemoryFeatures,
          VK_API_VERSION_1_1);
    check(d, "CmdSetDeviceMask", (void*)::vkCmdSetDeviceMask, VK_API_VERSION_1_1);
    check(d, "EnumeratePhysicalDeviceGroups", (void*)::vkEnumeratePhysicalDeviceGroups,
          VK_API_VERSION_1_1);
    check(d, "GetImageMemoryRequirements2", (void*)::vkGetImageMemoryRequirements2,
          VK_API_VERSION_1_1);
    check(d, "GetBufferMemoryRequirements2", (void*)::vkGetBufferMemoryRequirements2,
          VK_API_VERSION_1_1);
    check(d, "GetImageSparseMemoryRequirements2", (void*)::vkGetImageSparseMemoryRequirements2,
          VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceFeatures2", (void*)::vkGetPhysicalDeviceFeatures2,
          VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceProperties2", (void*)::vkGetPhysicalDeviceProperties2,
          VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceFormatProperties2", (void*)::vkGetPhysicalDeviceFormatProperties2,
          VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceImageFormatProperties2",
          (void*)::vkGetPhysicalDeviceImageFormatProperties2, VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceQueueFamilyProperties2",
          (void*)::vkGetPhysicalDeviceQueueFamilyProperties2, VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceMemoryProperties2", (void*)::vkGetPhysicalDeviceMemoryProperties2,
          VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceSparseImageFormatProperties2",
          (void*)::vkGetPhysicalDeviceSparseImageFormatProperties2, VK_API_VERSION_1_1);
    check(d, "TrimCommandPool", (void*)::vkTrimCommandPool, VK_API_VERSION_1_1);
    check(d, "GetDeviceQueue2", (void*)::vkGetDeviceQueue2, VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceExternalBufferProperties",
          (void*)::vkGetPhysicalDeviceExternalBufferProperties, VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceExternalFenceProperties",
          (void*)::vkGetPhysicalDeviceExternalFenceProperties, VK_API_VERSION_1_1);
    check(d, "GetPhysicalDeviceExternalSemaphoreProperties",
          (void*)::vkGetPhysicalDeviceExternalSemaphoreProperties, VK_API_VERSION_1_1);
    check(d, "CmdDispatchBase", (void*)::vkCmdDispatchBase, VK_API_VERSION_1_1);
    check(d, "CreateDescriptorUpdateTemplate", (void*)::vkCreateDescriptorUpdateTemplate,
          VK_API_VERSION_1_1);
    check(d, "DestroyDescriptorUpdateTemplate", (void*)::vkDestroyDescriptorUpdateTemplate,
          VK_API_VERSION_1_1);
    check(d, "UpdateDescriptorSetWithTemplate", (void*)::vkUpdateDescriptorSetWithTemplate,
          VK_API_VERSION_1_1);
    check(d, "GetDescriptorSetLayoutSupport", (void*)::vkGetDescriptorSetLayoutSupport,
          VK_API_VERSION_1_1);
    check(d, "CreateSamplerYcbcrConversion", (void*)::vkCreateSamplerYcbcrConversion,
          VK_API_VERSION_1_1);
    check(d, "DestroySamplerYcbcrConversion", (void*)::vkDestroySamplerYcbcrConversion,
          VK_API_VERSION_1_1);
#endif
#ifdef VK_VERSION_1_2
    check(d, "ResetQueryPool", (void*)::vkResetQueryPool, VK_API_VERSION_1_2);
    check(d, "GetSemaphoreCounterValue", (void*)::vkGetSemaphoreCounterValue, VK_API_VERSION_1_2);
    check(d, "WaitSemaphores", (void*)::vkWaitSemaphores, VK_API_VERSION_1_2);
    check(d, "SignalSemaphore", (void*)::vkSignalSemaphore, VK_API_VERSION_1_2);
    check(d, "GetBufferDeviceAddress", (void*)::vkGetBufferDeviceAddress, VK_API_VERSION_1_2);
    check(d, "GetBufferOpaqueCaptureAddress", (void*)::vkGetBufferOpaqueCaptureAddress,
          VK_API_VERSION_1_2);
    check(d, "GetDeviceMemoryOpaqueCaptureAddress", (void*)::vkGetDeviceMemoryOpaqueCaptureAddress,
          VK_API_VERSION_1_2);
    check(d, "CmdDrawIndirectCount", (void*)::vkCmdDrawIndirectCount, VK_API_VERSION_1_2);
    check(d, "CmdDrawIndexedIndirectCount", (void*)::vkCmdDrawIndexedIndirectCount,
          VK_API_VERSION_1_2);
    check(d, "CreateRenderPass2", (void*)::vkCreateRenderPass2, VK_API_VERSION_1_2);
    check(d, "CmdBeginRenderPass2", (void*)::vkCmdBeginRenderPass2, VK_API_VERSION_1_2);
    check(d, "CmdNextSubpass2", (void*)::vkCmdNextSubpass2, VK_API_VERSION_1_2);
    check(d, "CmdEndRenderPass2", (void*)::vkCmdEndRenderPass2, VK_API_VERSION_1_2);
#endif
#ifdef VK_VERSION_1_3
    check(d, "GetPhysicalDeviceToolProperties", (void*)::vkGetPhysicalDeviceToolProperties,
          VK_API_VERSION_1_3);
    check(d, "CreatePrivateDataSlot", (void*)::vkCreatePrivateDataSlot, VK_API_VERSION_1_3);
    check(d, "DestroyPrivateDataSlot", (void*)::vkDestroyPrivateDataSlot, VK_API_VERSION_1_3);
    check(d, "SetPrivateData", (void*)::vkSetPrivateData, VK_API_VERSION_1_3);
    check(d, "GetPrivateData", (void*)::vkGetPrivateData, VK_API_VERSION_1_3);
    check(d, "CmdPipelineBarrier2", (void*)::vkCmdPipelineBarrier2, VK_API_VERSION_1_3);
    check(d, "CmdWriteTimestamp2", (void*)::vkCmdWriteTimestamp2, VK_API_VERSION_1_3);
    check(d, "QueueSubmit2", (void*)::vkQueueSubmit2, VK_API_VERSION_1_3);
    check(d, "CmdCopyBuffer2", (void*)::vkCmdCopyBuffer2, VK_API_VERSION_1_3);
    check(d, "CmdCopyImage2", (void*)::vkCmdCopyImage2, VK_API_VERSION_1_3);
    check(d, "CmdCopyBufferToImage2", (void*)::vkCmdCopyBufferToImage2, VK_API_VERSION_1_3);
    check(d, "CmdCopyImageToBuffer2", (void*)::vkCmdCopyImageToBuffer2, VK_API_VERSION_1_3);
    check(d, "GetDeviceBufferMemoryRequirements", (void*)::vkGetDeviceBufferMemoryRequirements,
          VK_API_VERSION_1_3);
    check(d, "GetDeviceImageMemoryRequirements", (void*)::vkGetDeviceImageMemoryRequirements,
          VK_API_VERSION_1_3);
    check(d, "GetDeviceImageSparseMemoryRequirements",
          (void*)::vkGetDeviceImageSparseMemoryRequirements, VK_API_VERSION_1_3);
    check(d, "CmdSetEvent2", (void*)::vkCmdSetEvent2, VK_API_VERSION_1_3);
    check(d, "CmdResetEvent2", (void*)::vkCmdResetEvent2, VK_API_VERSION_1_3);
    check(d, "CmdWaitEvents2", (void*)::vkCmdWaitEvents2, VK_API_VERSION_1_3);
    check(d, "CmdBlitImage2", (void*)::vkCmdBlitImage2, VK_API_VERSION_1_3);
    check(d, "CmdResolveImage2", (void*)::vkCmdResolveImage2, VK_API_VERSION_1_3);
    check(d, "CmdBeginRendering", (void*)::vkCmdBeginRendering, VK_API_VERSION_1_3);
    check(d, "CmdEndRendering", (void*)::vkCmdEndRendering, VK_API_VERSION_1_3);
    check(d, "CmdSetCullMode", (void*)::vkCmdSetCullMode, VK_API_VERSION_1_3);
    check(d, "CmdSetFrontFace", (void*)::vkCmdSetFrontFace, VK_API_VERSION_1_3);
    check(d, "CmdSetPrimitiveTopology", (void*)::vkCmdSetPrimitiveTopology, VK_API_VERSION_1_3);
    check(d, "CmdSetViewportWithCount", (void*)::vkCmdSetViewportWithCount, VK_API_VERSION_1_3);
    check(d, "CmdSetScissorWithCount", (void*)::vkCmdSetScissorWithCount, VK_API_VERSION_1_3);
    check(d, "CmdBindVertexBuffers2", (void*)::vkCmdBindVertexBuffers2, VK_API_VERSION_1_3);
    check(d, "CmdSetDepthTestEnable", (void*)::vkCmdSetDepthTestEnable, VK_API_VERSION_1_3);
    check(d, "CmdSetDepthWriteEnable", (void*)::vkCmdSetDepthWriteEnable, VK_API_VERSION_1_3);
    check(d, "CmdSetDepthCompareOp", (void*)::vkCmdSetDepthCompareOp, VK_API_VERSION_1_3);
    check(d, "CmdSetDepthBoundsTestEnable", (void*)::vkCmdSetDepthBoundsTestEnable,
          VK_API_VERSION_1_3);
    check(d, "CmdSetStencilTestEnable", (void*)::vkCmdSetStencilTestEnable, VK_API_VERSION_1_3);
    check(d, "CmdSetStencilOp", (void*)::vkCmdSetStencilOp, VK_API_VERSION_1_3);
    check(d, "CmdSetRasterizerDiscardEnable", (void*)::vkCmdSetRasterizerDiscardEnable,
          VK_API_VERSION_1_3);
    check(d, "CmdSetDepthBiasEnable", (void*)::vkCmdSetDepthBiasEnable, VK_API_VERSION_1_3);
    check(d, "CmdSetPrimitiveRestartEnable", (void*)::vkCmdSetPrimitiveRestartEnable,
          VK_API_VERSION_1_3);
#endif
#ifdef VK_VERSION_1_4
    check(d, "MapMemory2", (void*)::vkMapMemory2, VK_API_VERSION_1_4);
    check(d, "UnmapMemory2", (void*)::vkUnmapMemory2, VK_API_VERSION_1_4);
    check(d, "GetDeviceImageSubresourceLayout", (void*)::vkGetDeviceImageSubresourceLayout,
          VK_API_VERSION_1_4);
    check(d, "GetImageSubresourceLayout2", (void*)::vkGetImageSubresourceLayout2,
          VK_API_VERSION_1_4);
    check(d, "CopyMemoryToImage", (void*)::vkCopyMemoryToImage, VK_API_VERSION_1_4);
    check(d, "CopyImageToMemory", (void*)::vkCopyImageToMemory, VK_API_VERSION_1_4);
    check(d, "CopyImageToImage", (void*)::vkCopyImageToImage, VK_API_VERSION_1_4);
    check(d, "TransitionImageLayout", (void*)::vkTransitionImageLayout, VK_API_VERSION_1_4);
    check(d, "CmdPushDescriptorSet", (void*)::vkCmdPushDescriptorSet, VK_API_VERSION_1_4);
    check(d, "CmdPushDescriptorSetWithTemplate", (void*)::vkCmdPushDescriptorSetWithTemplate,
          VK_API_VERSION_1_4);
    check(d, "CmdBindDescriptorSets2", (void*)::vkCmdBindDescriptorSets2, VK_API_VERSION_1_4);
    check(d, "CmdPushConstants2", (void*)::vkCmdPushConstants2, VK_API_VERSION_1_4);
    check(d, "CmdPushDescriptorSet2", (void*)::vkCmdPushDescriptorSet2, VK_API_VERSION_1_4);
    check(d, "CmdPushDescriptorSetWithTemplate2", (void*)::vkCmdPushDescriptorSetWithTemplate2,
          VK_API_VERSION_1_4);
    check(d, "CmdSetLineStipple", (void*)::vkCmdSetLineStipple, VK_API_VERSION_1_4);
    check(d, "CmdBindIndexBuffer2", (void*)::vkCmdBindIndexBuffer2, VK_API_VERSION_1_4);
    check(d, "GetRenderingAreaGranularity", (void*)::vkGetRenderingAreaGranularity,
          VK_API_VERSION_1_4);
    check(d, "CmdSetRenderingAttachmentLocations", (void*)::vkCmdSetRenderingAttachmentLocations,
          VK_API_VERSION_1_4);
    check(d, "CmdSetRenderingInputAttachmentIndices",
          (void*)::vkCmdSetRenderingInputAttachmentIndices, VK_API_VERSION_1_4);
#endif
}

} // namespace cheatah::gpu::vktest
